w3c/did

- index.html
Add initial content to the data model section on identifiers.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-spec/pull/29.html" title="Last updated on Oct 10, 2019, 12:51 AM UTC (f091255)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-spec/29/0c41898...f091255.html" title="Last updated on Oct 10, 2019, 12:51 AM UTC (f091255)">Diff</a>
> Add section on identifiers to Data Model section.

- index.html
Add initial content to the data model section on cryptographic keys.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-spec/pull/31.html" title="Last updated on Oct 10, 2019, 1:16 AM UTC (8aac222)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-spec/31/0c41898...8aac222.html" title="Last updated on Oct 10, 2019, 1:16 AM UTC (8aac222)">Diff</a>
> Add section on cryptographic keys.

- index.html
Add initial content to the data model section on services.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-spec/pull/32.html" title="Last updated on Oct 3, 2019, 9:01 PM UTC (120f022)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-spec/32/0c41898...120f022.html" title="Last updated on Oct 3, 2019, 9:01 PM UTC (120f022)">Diff</a>
> Add section on services to data model section.

- index.html
Fixes #43.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-spec/pull/71.html" title="Last updated on Oct 16, 2019, 9:42 AM UTC (5db853a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-spec/71/2ae47b7...5db853a.html" title="Last updated on Oct 16, 2019, 9:42 AM UTC (5db853a)">Diff</a>
> Clarify text about actions defined for DID Registry. Fix #43.

- index.html
fixes #74 
Signed-off-by: Brent <brent.zundel@gmail.com>
***
<a href="https://pr-preview.s3.amazonaws.com/brentzundel/did-spec/pull/78.html" title="Last updated on Oct 17, 2019, 6:00 PM UTC (5106911)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-spec/78/2658184...brentzundel:5106911.html" title="Last updated on Oct 17, 2019, 6:00 PM UTC (5106911)">Diff</a>
> restore author list

- index.html
Fixes #42 
Added sentence to clarify question of meaning that was raised in the issue.
Signed-off-by: Drummond Reed <drummond@connect.me>
***
<a href="https://pr-preview.s3.amazonaws.com/talltree/did-spec/pull/79.html" title="Last updated on Oct 17, 2019, 10:12 PM UTC (fe239b0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-spec/79/f41a80d...talltree:fe239b0.html" title="Last updated on Oct 17, 2019, 10:12 PM UTC (fe239b0)">Diff</a>
> PR to fix issue #42—clarifying meaning of a sentence in intro

- index.html
- terms.html
Fixes #50.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-spec/pull/73.html" title="Last updated on Oct 18, 2019, 9:55 PM UTC (9f17789)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-spec/73/e8aa51c...9f17789.html" title="Last updated on Oct 18, 2019, 9:55 PM UTC (9f17789)">Diff</a>
> Change capitalization of key terms to lowercase.

- index.html
- terms.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-spec/pull/77.html" title="Last updated on Oct 23, 2019, 1:23 AM UTC (df93787)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-spec/77/99a0873...df93787.html" title="Last updated on Oct 23, 2019, 1:23 AM UTC (df93787)">Diff</a>
> Ensure DID Controller is used consistently. Fix #37.

- index.html
- terms.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-spec/pull/82.html" title="Last updated on Oct 23, 2019, 2:07 AM UTC (c1dbcfe)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-spec/82/a45cd90...c1dbcfe.html" title="Last updated on Oct 23, 2019, 2:07 AM UTC (c1dbcfe)">Diff</a>
> Add "DID resolver" to terminology

- terms.html
(looks like an earlier copy&paste mistake)
> Fix DID query term definition

- .travis.yml
- ECHIDNA
Setting up echina (=automatic publication).
Beware: merging this means that, after this step _all_ merge to the master branch will start the automatic process to publish on `https://www.w3.org/TR/did-core/`.
(Good if we are all around when it happens the first time; unexpected problems may occur with an echidna setup :-)
> Initial setup for echidna

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/120.html" title="Last updated on Nov 25, 2019, 3:34 PM UTC (08464a7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/120/a8d0c28...08464a7.html" title="Last updated on Nov 25, 2019, 3:34 PM UTC (08464a7)">Diff</a>
> Comment the date so it's always today

- index.html
Grammar and punctuation changes, reformatting of info into lists, changing ordered lists to unordered lists, and line spacing changes
***
<a href="https://pr-preview.s3.amazonaws.com/grantnoble/did-core/pull/116.html" title="Last updated on Nov 25, 2019, 12:14 PM UTC (a9a07e8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/116/a8d0c28...grantnoble:a9a07e8.html" title="Last updated on Nov 25, 2019, 12:14 PM UTC (a9a07e8)">Diff</a>
> Decentralized Identifiers (DIDs) section review

- index.html
this was just really bugging me please someone merge it :)
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/121.html" title="Last updated on Nov 25, 2019, 5:00 PM UTC (e000805)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/121/979bfe3...e000805.html" title="Last updated on Nov 25, 2019, 5:00 PM UTC (e000805)">Diff</a>
> Fix respec errors on local links

- index.html
Wording and grammar changes,  some punctuation, spacing, line breaks, and line length updates
***
<a href="https://pr-preview.s3.amazonaws.com/grantnoble/did-core/pull/114.html" title="Last updated on Nov 19, 2019, 11:55 PM UTC (f56bf57)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/114/a8d0c28...grantnoble:f56bf57.html" title="Last updated on Nov 19, 2019, 11:55 PM UTC (f56bf57)">Diff</a>
> Data Model section editorial review

- index.html
Tried to bring in some consistency with the spacing of the p and section tags.
Line length updates.
Some minor wording and punctuation changes.
***
<a href="https://pr-preview.s3.amazonaws.com/grantnoble/did-core/pull/125.html" title="Last updated on Nov 26, 2019, 5:27 AM UTC (d88489e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/125/a8d0c28...grantnoble:d88489e.html" title="Last updated on Nov 26, 2019, 5:27 AM UTC (d88489e)">Diff</a>
> DID Document Syntax section review

- index.html
Line length updates.
Punctuation and wording changes.
***
<a href="https://pr-preview.s3.amazonaws.com/grantnoble/did-core/pull/126.html" title="Last updated on Nov 26, 2019, 6:47 AM UTC (595506d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/126/979bfe3...grantnoble:595506d.html" title="Last updated on Nov 26, 2019, 6:47 AM UTC (595506d)">Diff</a>
> DID methods section review

- index.html
Line length updates.
Wording changes
***
<a href="https://pr-preview.s3.amazonaws.com/grantnoble/did-core/pull/127.html" title="Last updated on Dec 1, 2019, 9:39 PM UTC (baca2b6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/127/979bfe3...grantnoble:baca2b6.html" title="Last updated on Dec 1, 2019, 9:39 PM UTC (baca2b6)">Diff</a>
> DID resolvers section review

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/110.html" title="Last updated on Dec 6, 2019, 3:41 PM UTC (008b918)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/110/d56304c...008b918.html" title="Last updated on Dec 6, 2019, 3:41 PM UTC (008b918)">Diff</a>
> Add key expression formats for Curve25519.

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/101.html" title="Last updated on Dec 6, 2019, 3:50 PM UTC (3eadfb7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/101/5b3bfcb...3eadfb7.html" title="Last updated on Dec 6, 2019, 3:50 PM UTC (3eadfb7)">Diff</a>
> Add key expression formats for secp256k1.

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/136.html" title="Last updated on Dec 6, 2019, 3:32 AM UTC (457d2ca)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/136/02b8613...457d2ca.html" title="Last updated on Dec 6, 2019, 3:32 AM UTC (457d2ca)">Diff</a>
> Fix markup issue

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/grantnoble/did-core/pull/132.html" title="Last updated on Dec 3, 2019, 2:24 AM UTC (09fb23b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/132/b8c3918...grantnoble:09fb23b.html" title="Last updated on Dec 3, 2019, 2:24 AM UTC (09fb23b)">Diff</a>
> Editorial Security Considerations section review

- index.html
- Line length changes
- Term linking
- Wording changes
- List updates
***
<a href="https://pr-preview.s3.amazonaws.com/grantnoble/did-core/pull/133.html" title="Last updated on Dec 3, 2019, 2:56 AM UTC (808ff5c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/133/b8c3918...grantnoble:808ff5c.html" title="Last updated on Dec 3, 2019, 2:56 AM UTC (808ff5c)">Diff</a>
> Editorial review of Privacy Considerations section

- index.html
- Line length changes
- Wording, grammar, and punctuation changes
- Removal of superfluous "Example" intros
- Other misc changes
***
<a href="https://pr-preview.s3.amazonaws.com/grantnoble/did-core/pull/141.html" title="Last updated on Jan 7, 2020, 12:56 AM UTC (d566763)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/141/601e0d9...grantnoble:d566763.html" title="Last updated on Jan 7, 2020, 12:56 AM UTC (d566763)">Diff</a>
> DID Documents section editorial re-review

- index.html
This is suggested additional text to address issue #149
~~I've somehow screwed up the formatting on this section too, so I'd appreciate some help learning what's the easiest way to format the HTML for PRs as well.~~
***
<a href="https://pr-preview.s3.amazonaws.com/kdenhartog/did-core/pull/150.html" title="Last updated on Feb 12, 2020, 9:54 PM UTC (1526ba9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/150/e54cf87...kdenhartog:1526ba9.html" title="Last updated on Feb 12, 2020, 9:54 PM UTC (1526ba9)">Diff</a>
> detail how unsupported CRUD operations should be defined

- index.html
This adds language to describe the nature of representations as well as subsections for production and consumption for each representation. I have proposed text for the JSON section, and I want to point out the fact that the production and consumption aspects are in fact subtly different from each other. I also attempted to add text for the JSON-LD section, and would be glad to have input from JSON-LD developers about what is missing here. I have left the CBOR empty for the moment (but with stubs).
I removed much of the previous JSON-LD section as the text in question was either an explanation of JSON-LD (which is not needed in this document), and extolling of the benefits of JSON-LD (which does not belong in this document), or an explanation of how to do extensions with JSON-LD (which …
> Add producer/consumer language

- index.html
Addresses #98, #152.
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Mar 12, 2020, 7:42 PM UTC)_.
<details>
:rotating_light: [Spec Generator](https://www.w3.org/2015/labs/) - Spec Generator is the web service used to build specs that rely on ReSpec.
:link: [Related URL](https://labs.w3.org/spec-generator/?type=respec&url=https%3A%2F%2Frawcdn.githack.com%2Fw3c%2Fdid-core%2Fd8935265536dbec55ae00e4484633f957423bef3%2Findex.html%3FisPreview%3Dtrue)
```
<html><body><h1>504 Gateway Time-out</h1>
The server didn't respond in time.
</body></html>
```
_If you don't have enough information above to solve the error by …
> Clarify use of colon in method-specific-id.

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/219.html" title="Last updated on Mar 19, 2020, 12:39 AM UTC (c8a2508)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/219/414798f...c8a2508.html" title="Last updated on Mar 19, 2020, 12:39 AM UTC (c8a2508)">Diff</a>
> Add support for relative DID URLs. Fix #201.

- index.html
***
:boom: ###
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Mar 17, 2020, 12:28 PM UTC)_.
<details>
:rotating_light: [HTML Diff Service](http://services.w3.org/htmldiff) - The HTML Diff Service is used to create HTML diffs of the spec changes suggested in a pull request.
:link: [Related URL](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fpr-preview.s3.amazonaws.com%2Fw3c%2Fdid-core%2Fpull%2F226%2F93bc34c.html&doc2=https%3A%2F%2Fpr-preview.s3.amazonaws.com%2Fw3c%2Fdid-core%2Fpull%2F226.html)
_If you don't have enough information above to solve the error by yourself (or to understand to which web service the …
> Remove the term "CRUD". Addresses #167.

- index.html
This is a stale issue. In issue 177 @rhiaro proposed removing this section of text. 
Closes #177
***
<a href="https://pr-preview.s3.amazonaws.com/kdenhartog/did-core/pull/229.html" title="Last updated on Mar 18, 2020, 9:10 AM UTC (cdecd41)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/229/93bc34c...kdenhartog:cdecd41.html" title="Last updated on Mar 18, 2020, 9:10 AM UTC (cdecd41)">Diff</a>
> remove issue referencing object capabilities

- index.html
Very minor editorial update to the issues list at the end of the document
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/237.html" title="Last updated on Mar 23, 2020, 2:06 PM UTC (f59cd30)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/237/1b81426...f59cd30.html" title="Last updated on Mar 23, 2020, 2:06 PM UTC (f59cd30)">Diff</a>
> Remove closed issues from the list

- index.html
See discussion in #134
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/225.html" title="Last updated on Mar 18, 2020, 7:58 AM UTC (be17366)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/225/93bc34c...be17366.html" title="Last updated on Mar 18, 2020, 7:58 AM UTC (be17366)">Diff</a>
> Make id mandatory for public keys and service endpoints

- index.html
Security Considerations section with the caveats about using encrypted data in DID Documents. Addresses concerns in #25
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/228.html" title="Last updated on Mar 23, 2020, 3:41 PM UTC (e9f4825)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/228/93bc34c...e9f4825.html" title="Last updated on Mar 23, 2020, 3:41 PM UTC (e9f4825)">Diff</a>
> Section about encrypted data in DID docs

- index.html
Signed-off-by: Oskar van Deventer <46109652+Oskar-van-Deventer@users.noreply.github.com>
clarify what a DID identifies
***
<a href="https://pr-preview.s3.amazonaws.com/Oskar-van-Deventer/did-core/pull/213.html" title="Last updated on Mar 19, 2020, 8:23 AM UTC (2d51aa7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/213/90c68be...Oskar-van-Deventer:2d51aa7.html" title="Last updated on Mar 19, 2020, 8:23 AM UTC (2d51aa7)">Diff</a>
> Clarify what a DID identifies

- index.html
This PR adds additional details to address issue #16. It's intention is to
further guide developers with non-normative statements about how serviceEndpoints
should work so that they don't create privacy concerns.
Closes #16
***
<a href="https://pr-preview.s3.amazonaws.com/kdenhartog/did-core/pull/232.html" title="Last updated on Apr 10, 2020, 12:43 AM UTC (5840b99)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/232/93bc34c...kdenhartog:5840b99.html" title="Last updated on Apr 10, 2020, 12:43 AM UTC (5840b99)">Diff</a>
> address privacy concerns with serviceEndpoints

- index.html
- terms.html
Issue #182 asks for a definition of the commonly used term 'resource'. I've drafted one based on comments in the issue, but I don't actually think it's correct or an obvious consensus. Just thought I'd make the PR to shuffle the discussion along a bit :)
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/243.html" title="Last updated on Apr 20, 2020, 7:19 AM UTC (41f84aa)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/243/05e1a3a...41f84aa.html" title="Last updated on Apr 20, 2020, 7:19 AM UTC (41f84aa)">Diff</a>
> Working dfn for 'resource', for #182

- common.js
- index.html
Signed-off-by: Drummond Reed <drummond@connect.me>
First draft of the new Section 6 that we agreed to add to the spec after the Amsterdam F2F meeting.
***
<a href="https://pr-preview.s3.amazonaws.com/talltree/did-core/pull/241.html" title="Last updated on Apr 21, 2020, 8:30 PM UTC (dba5548)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/241/fd4c5cf...talltree:dba5548.html" title="Last updated on Apr 21, 2020, 8:30 PM UTC (dba5548)">Diff</a>
> initial text for section 6

- index.html
Fixes #161
***
<a href="https://pr-preview.s3.amazonaws.com/selfissued/did-core/pull/278.html" title="Last updated on May 12, 2020, 2:21 AM UTC (ced789a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/278/48bc712...selfissued:ced789a.html" title="Last updated on May 12, 2020, 2:21 AM UTC (ced789a)">Diff</a>
> Remove uses of undefined terms graph-based and tree-based

- index.html
Fixes #168
***
<a href="https://pr-preview.s3.amazonaws.com/selfissued/did-core/pull/279.html" title="Last updated on May 12, 2020, 2:46 AM UTC (2a01222)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/279/48bc712...selfissued:2a01222.html" title="Last updated on May 12, 2020, 2:46 AM UTC (2a01222)">Diff</a>
> Simplify description of revoked keys

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/305.html" title="Last updated on May 31, 2020, 2:57 PM UTC (d846737)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/305/490cccb...d846737.html" title="Last updated on May 31, 2020, 2:57 PM UTC (d846737)">Diff</a>
> Remove proof as it is specific to Linked Data Proofs. Fixes #293

- index.html
added CBOR section.  Not totally complete but I could use some help validating the CDDL and tag 98 syntax.  Thanks!   @kdenhartog @selfissued @jricher
***
<a href="https://pr-preview.s3.amazonaws.com/jonnycrunch/did-core/pull/282.html" title="Last updated on Jun 9, 2020, 3:22 PM UTC (3b4a2b6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/282/48bc712...jonnycrunch:3b4a2b6.html" title="Last updated on Jun 9, 2020, 3:22 PM UTC (3b4a2b6)">Diff</a>
> Added CBOR section 

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/308.html" title="Last updated on Jun 2, 2020, 4:13 PM UTC (de1f008)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/308/490cccb...de1f008.html" title="Last updated on Jun 2, 2020, 4:13 PM UTC (de1f008)">Diff</a>
> Disallow expressing revoked keys using a verification relationship.

- index.html
Initial draft text outlining the different verification relationships. I've done a bit of shifting of the sections as well to group the verifiable relationships together better, but haven't modified the text in there.
***
<a href="https://pr-preview.s3.amazonaws.com/kdenhartog/did-core/pull/312.html" title="Last updated on Jun 10, 2020, 3:25 AM UTC (c012a23)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/312/7a4bac4...kdenhartog:c012a23.html" title="Last updated on Jun 10, 2020, 3:25 AM UTC (c012a23)">Diff</a>
> add core properties verifiable relationship sections

- index.html
Trying again... rewording to make better (I think).
***
<a href="https://pr-preview.s3.amazonaws.com/CholoTook/did-core/pull/267.html" title="Last updated on Jul 3, 2020, 1:09 PM UTC (c573920)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/267/515db7b...CholoTook:c573920.html" title="Last updated on Jul 3, 2020, 1:09 PM UTC (c573920)">Diff</a>
> Put key points up front

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/davidlehn/did-core/pull/346.html" title="Last updated on Jul 13, 2020, 5:40 PM UTC (cc16a4c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/346/9d8e245...davidlehn:cc16a4c.html" title="Last updated on Jul 13, 2020, 5:40 PM UTC (cc16a4c)">Diff</a>
> Fix spelling.

- index.html
Fixes #176
***
<a href="https://pr-preview.s3.amazonaws.com/selfissued/did-core/pull/369.html" title="Last updated on Aug 11, 2020, 12:46 AM UTC (fd1ebf6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/369/3cc2641...selfissued:fd1ebf6.html" title="Last updated on Aug 11, 2020, 12:46 AM UTC (fd1ebf6)">Diff</a>
> Remove unsubstantiated statement about protecting against attacks when compromised

- index.html
adds examples of did documents with verification methods that are defined in the did core context.
adds examples of verifiable credentials leveraging those verification methods.
adds examples of encryption using JWE leveraging verification methods.
adds placeholder for ZKPs (may get removed if we can't provide examples).
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/377.html" title="Last updated on Aug 20, 2020, 9:45 PM UTC (3f129ae)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/377/4dedfe5...3f129ae.html" title="Last updated on Aug 20, 2020, 9:45 PM UTC (3f129ae)">Diff</a>
> Add examples

- index.html
Changed the respec reference to the latest version (2020-09-15)
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/395.html" title="Last updated on Sep 16, 2020, 9:23 AM UTC (6ec6968)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/395/9f98243...6ec6968.html" title="Last updated on Sep 16, 2020, 9:23 AM UTC (6ec6968)">Diff</a>
> Updated the respec reference

- index.html
addresses #356
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/415.html" title="Last updated on Sep 23, 2020, 2:08 PM UTC (900ea11)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/415/14b5eda...900ea11.html" title="Last updated on Sep 23, 2020, 2:08 PM UTC (900ea11)">Diff</a>
> Forbid multiple key formats in the same verification method

- w3c.json
https://github.com/w3c/did-core/blob/master/w3c.json#L5
https://github.com/w3c/did-core/blob/master/ECHIDNA#L2
https://github.com/w3c/did-core/blob/master/index.html#L34
I believe these all need to match, for echidna to work correctly.
> Fix echidna

- index.html
- terms.html
Thanks to @iherman for these in #401
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/414.html" title="Last updated on Oct 25, 2020, 9:43 AM UTC (2049d55)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/414/c764c67...2049d55.html" title="Last updated on Oct 25, 2020, 9:43 AM UTC (2049d55)">Diff</a>
> Editorial updates from Ivan

- index.html
Normative statement tweaks in the core properties section based on feedback from @kdenhartog and @msporny; see #384
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/429.html" title="Last updated on Oct 18, 2020, 3:57 PM UTC (7cf35fc)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/429/c764c67...7cf35fc.html" title="Last updated on Oct 18, 2020, 3:57 PM UTC (7cf35fc)">Diff</a>
> normative statements: Core properties section

- index.html
Running jsonld-checker.com on the spec files reveals that a couple of JSON-LD objects in the examples are invalid. See https://www.jsonld-checker.com/?tab=1&url=https%3A%2F%2Fgithub.com%2Fw3c%2Fdid-core%2Fblob%2Fmaster%2Findex.html
Namely:
- [The UserHubEndpoint object](https://www.jsonld-checker.com/?json=%257B%250A%2520%2520%2522%2540context%2522%253A%2520%2522https%253A%252F%252Fschema.identity.foundation%252Fhub%2522%252C%250A%2520%2520%2522type%2522%253A%2520%2522UserHubEndpoint%2522%252C%250A%2520%2520%2522instances%2522%253A%2520%255B%250A%2520%2520%2520%2520%2522did%253Aexample%253A456%2522%252C%250A%2520%2520%2520%2520%2522did%253Aexample%253A789%2522%250A%2520%2520%255D%250A%257D&tab=0) which context (https://schema.identity.foundation/hub) is not a resolvable URL. We should …
> Fix JSON-LD object in the spec

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/442.html" title="Last updated on Oct 25, 2020, 12:39 PM UTC (5e7e475)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/442/c764c67...5e7e475.html" title="Last updated on Oct 25, 2020, 12:39 PM UTC (5e7e475)">Diff</a>
> editorial: fix stray link to issues

- index.html
A note, for #411. Not sure if I've got the language exactly right here, pointers welcome.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/443.html" title="Last updated on Oct 25, 2020, 1:21 PM UTC (00dee90)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/443/c764c67...00dee90.html" title="Last updated on Oct 25, 2020, 1:21 PM UTC (00dee90)">Diff</a>
> editorial: Clarify importance of ordering of property values

- common.js
- index.html
I ran through #403 and this PR contains the suggested changes that are editorial and uncontroversial; see individual commits for details.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/441.html" title="Last updated on Nov 2, 2020, 8:51 AM UTC (2593704)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/441/58225f1...2593704.html" title="Last updated on Nov 2, 2020, 8:51 AM UTC (2593704)">Diff</a>
> Editorial updates from Ivan, #2

- index.html
Per WG resolution at https://www.w3.org/2019/did-wg/Meetings/Minutes/2020-10-06-did#resolution1
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/444.html" title="Last updated on Nov 2, 2020, 12:06 PM UTC (dd3ae2d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/444/2a3ca5d...dd3ae2d.html" title="Last updated on Nov 2, 2020, 12:06 PM UTC (dd3ae2d)">Diff</a>
> privacy: Add privacy concerns about 'type' (and similar) property.

- index.html
Removes closed issues from the list at the end as well as inline in the spec sections. Ticks off this point in #403 (for now..)
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/445.html" title="Last updated on Oct 27, 2020, 12:43 PM UTC (7c4c4dc)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/445/5dd10b5...7c4c4dc.html" title="Last updated on Oct 27, 2020, 12:43 PM UTC (7c4c4dc)">Diff</a>
> editorial: Remove closed issues

- index.html
Tries to make use of sections more consistent and improve headings and informative text.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/471.html" title="Last updated on Nov 24, 2020, 10:20 PM UTC (a8731d6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/471/002b9f0...a8731d6.html" title="Last updated on Nov 24, 2020, 10:20 PM UTC (a8731d6)">Diff</a>
> Minor editorial reshuffling in Core Properties

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/476.html" title="Last updated on Dec 13, 2020, 8:33 PM UTC (4d5c073)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/476/05d75f3...4d5c073.html" title="Last updated on Dec 13, 2020, 8:33 PM UTC (4d5c073)">Diff</a>
> Align CBOR production/consumption rules with rest of specification.

- index.html
Small bugs that stopped the latest echidna build
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/493.html" title="Last updated on Dec 14, 2020, 1:48 PM UTC (aad6636)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/493/2eef04c...aad6636.html" title="Last updated on Dec 14, 2020, 1:48 PM UTC (aad6636)">Diff</a>
> markup: Fix bugs

- index.html
Addresses https://github.com/w3c/did-core/issues/456
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/486.html" title="Last updated on Dec 14, 2020, 6:50 PM UTC (73c35b3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/486/16ba782...73c35b3.html" title="Last updated on Dec 14, 2020, 6:50 PM UTC (73c35b3)">Diff</a>
> Add note on representation properties lexical and value space

- index.html
As subject reads
***
<a href="https://pr-preview.s3.amazonaws.com/shigeya/did-core/pull/497.html" title="Last updated on Dec 14, 2020, 2:43 PM UTC (f1daae4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/497/2eef04c...shigeya:f1daae4.html" title="Last updated on Dec 14, 2020, 2:43 PM UTC (f1daae4)">Diff</a>
> Minor typo fixes to Sec. 1, 6 and 7

- index.html
Addresses issue #483
***
<a href="https://pr-preview.s3.amazonaws.com/oed/did-core/pull/508.html" title="Last updated on Dec 22, 2020, 3:21 PM UTC (28b10c9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/508/6434f17...oed:28b10c9.html" title="Last updated on Dec 22, 2020, 3:21 PM UTC (28b10c9)">Diff</a>
> Add additional Metadata properties, fix #483

- index.html
This is editorial..
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/512.html" title="Last updated on Dec 21, 2020, 12:04 PM UTC (7fac2bb)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/512/6434f17...7fac2bb.html" title="Last updated on Dec 21, 2020, 12:04 PM UTC (7fac2bb)">Diff</a>
> Add StandICT.eu contract number.

- index.html
This is editorial..
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/513.html" title="Last updated on Dec 21, 2020, 12:05 PM UTC (f6826f9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/513/6434f17...f6826f9.html" title="Last updated on Dec 21, 2020, 12:05 PM UTC (f6826f9)">Diff</a>
> Add SVIP contract number.

- index.html
closes #502
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/514.html" title="Last updated on Jan 3, 2021, 4:36 PM UTC (e636738)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/514/6434f17...e636738.html" title="Last updated on Jan 3, 2021, 4:36 PM UTC (e636738)">Diff</a>
> rewords usage of decentralized extensions

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/555.html" title="Last updated on Jan 18, 2021, 12:15 PM UTC (4a6b3d8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/555/af9c06b...4a6b3d8.html" title="Last updated on Jan 18, 2021, 12:15 PM UTC (4a6b3d8)">Diff</a>
> markup: fix bugs that are causing echidna to fail

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/557.html" title="Last updated on Jan 18, 2021, 7:13 PM UTC (6991a1f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/557/5ffc8be...6991a1f.html" title="Last updated on Jan 18, 2021, 7:13 PM UTC (6991a1f)">Diff</a>
> markup: really fix echidna this time

- index.html
Attempt to make things a bit more succint and easier to read.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/535.html" title="Last updated on Jan 17, 2021, 9:51 PM UTC (b0d67d7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/535/af9c06b...b0d67d7.html" title="Last updated on Jan 17, 2021, 9:51 PM UTC (b0d67d7)">Diff</a>
> Editorial cleanup of security & privacy sections

- index.html
Described two possible cases where 1) there is no update, and
2) an update performed within less than one second after creation.
Part of the text by Amy Guy. thanks.
***
<a href="https://pr-preview.s3.amazonaws.com/shigeya/did-core/pull/540.html" title="Last updated on Jan 20, 2021, 12:01 AM UTC (72e36d7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/540/c8bc6b1...shigeya:72e36d7.html" title="Last updated on Jan 20, 2021, 12:01 AM UTC (72e36d7)">Diff</a>
> Address issue #495

- index.html
@dhh1128 I assume this is what you meant in https://github.com/w3c/did-core/pull/515?
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/541.html" title="Last updated on Jan 18, 2021, 9:54 AM UTC (35f3b53)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/541/af9c06b...35f3b53.html" title="Last updated on Jan 18, 2021, 9:54 AM UTC (35f3b53)">Diff</a>
> Change "herd immunity" to "herd privacy"

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/csuwildcat/did-core/pull/542.html" title="Last updated on Jan 24, 2021, 4:28 PM UTC (f1cd363)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/542/c8bc6b1...csuwildcat:f1cd363.html" title="Last updated on Jan 24, 2021, 4:28 PM UTC (f1cd363)">Diff</a>
> Add recommendation notes for equivalence properties

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/Diiaablo95/did-core/pull/558.html" title="Last updated on Jan 19, 2021, 9:46 AM UTC (fc18acd)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/558/4ecfda7...Diiaablo95:fc18acd.html" title="Last updated on Jan 19, 2021, 9:46 AM UTC (fc18acd)">Diff</a>
> Fix a couple of minor errors in the README.

- index.html
Resolves Issue #559
***
<a href="https://pr-preview.s3.amazonaws.com/shigeya/did-core/pull/560.html" title="Last updated on Jan 19, 2021, 3:53 PM UTC (01ab2a2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/560/4ecfda7...shigeya:01ab2a2.html" title="Last updated on Jan 19, 2021, 3:53 PM UTC (01ab2a2)">Diff</a>
> Adding description of the resolve forms

- index.html
sfor --> for
***
<a href="https://pr-preview.s3.amazonaws.com/christianpaquin/did-core/pull/578.html" title="Last updated on Jan 25, 2021, 10:02 PM UTC (726513d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/578/5b7ede4...christianpaquin:726513d.html" title="Last updated on Jan 25, 2021, 10:02 PM UTC (726513d)">Diff</a>
> Fixed typo in index.html.

- index.html
Small change to abstract to make it more accurate
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/576.html" title="Last updated on Jan 31, 2021, 10:54 PM UTC (5baac48)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/576/db9c492...5baac48.html" title="Last updated on Jan 31, 2021, 10:54 PM UTC (5baac48)">Diff</a>
> abstract: update for accuracy

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/588.html" title="Last updated on Feb 1, 2021, 4:34 PM UTC (b1265bc)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/588/39877b1...b1265bc.html" title="Last updated on Feb 1, 2021, 4:34 PM UTC (b1265bc)">Diff</a>
> editorial: issue markers for proving control sections, for #583

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/602.html" title="Last updated on Feb 7, 2021, 4:40 PM UTC (e291eae)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/602/59687a4...e291eae.html" title="Last updated on Feb 7, 2021, 4:40 PM UTC (e291eae)">Diff</a>
> Add bbs examples

- index.html
Fixes #598
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/603.html" title="Last updated on Feb 12, 2021, 2:27 PM UTC (1bf5b38)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/603/1dda7f5...1bf5b38.html" title="Last updated on Feb 12, 2021, 2:27 PM UTC (1bf5b38)">Diff</a>
> Fix appendices sections

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/608.html" title="Last updated on Feb 12, 2021, 2:32 PM UTC (20ab402)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/608/6645c05...20ab402.html" title="Last updated on Feb 12, 2021, 2:32 PM UTC (20ab402)">Diff</a>
> Editorial clean up of Abstract section.

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/609.html" title="Last updated on Feb 12, 2021, 2:42 PM UTC (93dc906)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/609/6645c05...93dc906.html" title="Last updated on Feb 12, 2021, 2:42 PM UTC (93dc906)">Diff</a>
> Prepare Status of the Document section for Candidate Recommendation.

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/611.html" title="Last updated on Feb 12, 2021, 3:01 PM UTC (3fe2caa)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/611/6645c05...3fe2caa.html" title="Last updated on Feb 12, 2021, 3:01 PM UTC (3fe2caa)">Diff</a>
> Editorial rework of Introduction section.

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/614.html" title="Last updated on Feb 12, 2021, 4:58 PM UTC (3e206d3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/614/6645c05...3e206d3.html" title="Last updated on Feb 12, 2021, 4:58 PM UTC (3e206d3)">Diff</a>
> Editorial clean up for Design Goals section.

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/617.html" title="Last updated on Feb 12, 2021, 5:12 PM UTC (9bd7a96)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/617/3858d12...9bd7a96.html" title="Last updated on Feb 12, 2021, 5:12 PM UTC (9bd7a96)">Diff</a>
> Fix editorial issues with Conformance section.

- index.html
- terms.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/619.html" title="Last updated on Feb 12, 2021, 5:26 PM UTC (a1c3018)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/619/5d0cdbc...a1c3018.html" title="Last updated on Feb 12, 2021, 5:26 PM UTC (a1c3018)">Diff</a>
> Fix editorial issues with Terminology section.

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/629.html" title="Last updated on Feb 16, 2021, 2:44 PM UTC (47cddc3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/629/1dda7f5...47cddc3.html" title="Last updated on Feb 16, 2021, 2:44 PM UTC (47cddc3)">Diff</a>
> Fix editorial issues in Relative DID URLs section.

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/630.html" title="Last updated on Feb 16, 2021, 2:46 PM UTC (8a4dbae)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/630/9b373a1...8a4dbae.html" title="Last updated on Feb 16, 2021, 2:46 PM UTC (8a4dbae)">Diff</a>
> Fix editorial issues in Core Properties section.

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/631.html" title="Last updated on Feb 16, 2021, 2:53 PM UTC (96103e0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/631/b3550b1...96103e0.html" title="Last updated on Feb 16, 2021, 2:53 PM UTC (96103e0)">Diff</a>
> Fix editorial issues in Data Model section.

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/636.html" title="Last updated on Feb 16, 2021, 3:15 PM UTC (a9b7c74)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/636/448648e...a9b7c74.html" title="Last updated on Feb 16, 2021, 3:15 PM UTC (a9b7c74)">Diff</a>
> Fix editorial issues with Verification Relationship intro section.

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/637.html" title="Last updated on Feb 16, 2021, 3:18 PM UTC (41716a7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/637/9b373a1...41716a7.html" title="Last updated on Feb 16, 2021, 3:18 PM UTC (41716a7)">Diff</a>
> Fix editorial issues with Authentication section.

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/638.html" title="Last updated on Feb 16, 2021, 3:21 PM UTC (6932b3b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/638/9b373a1...6932b3b.html" title="Last updated on Feb 16, 2021, 3:21 PM UTC (6932b3b)">Diff</a>
> Fix minor editorial issues with Assertion section.

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/639.html" title="Last updated on Feb 16, 2021, 3:23 PM UTC (0b0ca72)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/639/d355bda...0b0ca72.html" title="Last updated on Feb 16, 2021, 3:23 PM UTC (0b0ca72)">Diff</a>
> Fix editorial issues with Key Agreement section.

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/640.html" title="Last updated on Feb 16, 2021, 3:27 PM UTC (5e93833)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/640/d355bda...5e93833.html" title="Last updated on Feb 16, 2021, 3:27 PM UTC (5e93833)">Diff</a>
> Fix editorial issues with Capability Invocation section.

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/641.html" title="Last updated on Feb 16, 2021, 3:30 PM UTC (645fdab)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/641/d355bda...645fdab.html" title="Last updated on Feb 16, 2021, 3:30 PM UTC (645fdab)">Diff</a>
> Fix editorial issues with Capability Delegation section.

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/TallTed/did-core/pull/652.html" title="Last updated on Feb 15, 2021, 9:09 PM UTC (f56a8ac)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/652/d355bda...TallTed:f56a8ac.html" title="Last updated on Feb 15, 2021, 9:09 PM UTC (f56a8ac)">Diff</a>
> (editorial) add a missing "a" article

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/TallTed/did-core/pull/651.html" title="Last updated on Feb 15, 2021, 8:52 PM UTC (8d224e2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/651/d355bda...TallTed:8d224e2.html" title="Last updated on Feb 15, 2021, 8:52 PM UTC (8d224e2)">Diff</a>
> (editorial) minor punctuation and language fixes

- index.html
happened in #616
***
<a href="https://pr-preview.s3.amazonaws.com/TallTed/did-core/pull/658.html" title="Last updated on Feb 16, 2021, 4:08 PM UTC (e245c1d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/658/9f78b2c...TallTed:e245c1d.html" title="Last updated on Feb 16, 2021, 4:08 PM UTC (e245c1d)">Diff</a>
> (editorial) restore apparently accidental deletion

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/TallTed/did-core/pull/659.html" title="Last updated on Feb 16, 2021, 4:34 PM UTC (41ff06e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/659/9f78b2c...TallTed:41ff06e.html" title="Last updated on Feb 16, 2021, 4:34 PM UTC (41ff06e)">Diff</a>
> (editorial) language fixes too late for #631

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/TallTed/did-core/pull/661.html" title="Last updated on Feb 16, 2021, 5:18 PM UTC (581a845)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/661/9f78b2c...TallTed:581a845.html" title="Last updated on Feb 16, 2021, 5:18 PM UTC (581a845)">Diff</a>
> (editorial) capabilityDelegation language (+ line lengths)

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/665.html" title="Last updated on Feb 19, 2021, 1:30 AM UTC (27b5fe4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/665/e5903fa...27b5fe4.html" title="Last updated on Feb 19, 2021, 1:30 AM UTC (27b5fe4)">Diff</a>
> Change note on order to advisement

- index.html
Minor editorial change proposals on section 1
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/671.html" title="Last updated on Feb 18, 2021, 3:02 PM UTC (e1dde6f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/671/bb89040...e1dde6f.html" title="Last updated on Feb 18, 2021, 3:02 PM UTC (e1dde6f)">Diff</a>
> Minor editorial change proposals on section 1

- ECHIDNA
https://github.com/w3c/did-core/commit/56d35ff0454da6e36c70e60e238fafe19a62a0b4 renamed a SVG. That PR updates the Echidna manifest accordingly
> Update Echidna manifest after figure replacement

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/davidlehn/did-core/pull/633.html" title="Last updated on Feb 26, 2021, 5:41 PM UTC (d3114f1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/633/ed12dd5...davidlehn:d3114f1.html" title="Last updated on Feb 26, 2021, 5:41 PM UTC (d3114f1)">Diff</a>
> Various cleanups.

- index.html
This is meant to address #698.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/702.html" title="Last updated on Feb 26, 2021, 3:47 PM UTC (f4e4515)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/702/ed12dd5...f4e4515.html" title="Last updated on Feb 26, 2021, 3:47 PM UTC (f4e4515)">Diff</a>
> Add language about specifying DID URL path semantics.

- index.html
This PR creates an Acknowledgements section in the appendix as the Director will most likely object to acknowledgements in the Status of the Document section (where they are today). This is an editorial change.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/704.html" title="Last updated on Feb 26, 2021, 4:44 PM UTC (bab1750)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/704/ed12dd5...bab1750.html" title="Last updated on Feb 26, 2021, 4:44 PM UTC (bab1750)">Diff</a>
> Create acknowledgements section.

- index.html
My eyes caught this. let me submit before I forget...
***
<a href="https://pr-preview.s3.amazonaws.com/shigeya/did-core/pull/714.html" title="Last updated on Mar 19, 2021, 12:53 AM UTC (2184abe)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/714/10487e0...shigeya:2184abe.html" title="Last updated on Mar 19, 2021, 12:53 AM UTC (2184abe)">Diff</a>
> Minor editorial fix: removing superfluous close bracket

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/716.html" title="Last updated on Mar 26, 2021, 8:54 AM UTC (73c27cc)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/716/10487e0...73c27cc.html" title="Last updated on Mar 26, 2021, 8:54 AM UTC (73c27cc)">Diff</a>
> Apply small editorial fixes in the Resolution section.

- index.html
Addresses https://github.com/w3c/did-core/issues/717.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/720.html" title="Last updated on Mar 30, 2021, 11:44 AM UTC (e4a7df7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/720/10487e0...e4a7df7.html" title="Last updated on Mar 30, 2021, 11:44 AM UTC (e4a7df7)">Diff</a>
> Clarify that equivalentId and canonicalId are optional.

- index.html
Related to issue #723.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/725.html" title="Last updated on Apr 25, 2021, 7:12 PM UTC (9fdab11)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/725/10487e0...9fdab11.html" title="Last updated on Apr 25, 2021, 7:12 PM UTC (9fdab11)">Diff</a>
> Change "minimal" -> "simple" in DID Document description.

- index.html
- terms.html
Addresses issue #721.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/730.html" title="Last updated on May 7, 2021, 9:55 PM UTC (647c465)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/730/fddcfc0...647c465.html" title="Last updated on May 7, 2021, 9:55 PM UTC (647c465)">Diff</a>
> Add definition of amplification attack.

- index.html
- terms.html
This is being raised to address issue #712.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/732.html" title="Last updated on May 14, 2021, 8:28 PM UTC (a6b5d21)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/732/fddcfc0...a6b5d21.html" title="Last updated on May 14, 2021, 8:28 PM UTC (a6b5d21)">Diff</a>
> Add cryptographic suite definition.

- index.html
Partial editorial cleanup to appendices tracked as issue #728. This also addresses issue #583.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/736.html" title="Last updated on May 22, 2021, 2:47 PM UTC (1b96259)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/736/ab18a18...1b96259.html" title="Last updated on May 22, 2021, 2:47 PM UTC (1b96259)">Diff</a>
> Update Security Considerations introduction.

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/737.html" title="Last updated on May 16, 2021, 4:15 PM UTC (6cdfc20)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/737/ab18a18...6cdfc20.html" title="Last updated on May 16, 2021, 4:15 PM UTC (6cdfc20)">Diff</a>
> Update Choosing DID Resolvers section.

- index.html
Partial editorial cleanup to appendices tracked as issue #728. This also addresses issue #583.
This section was a bit of a mess and required a fairly significant rewrite... I tried to save what I could, much of the language was quite old and represented thinking from 3+ years ago. I tried to update the language to be less prescriptive, point to sections that have been created to address each item, and remove the concept of "proving control over a key" -- 'cause that's not really a use case, it's just a smaller part of larger use cases such as authentication and authorization, which we already have sections that go to lengths to talk about those mechanisms elsewhere in the spec (so I pointed there).
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/738.html" title="Last …
> Update Proving Control and Binding section.

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/739.html" title="Last updated on May 16, 2021, 6:22 PM UTC (c03dd64)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/739/ab18a18...c03dd64.html" title="Last updated on May 16, 2021, 6:22 PM UTC (c03dd64)">Diff</a>
> Update non-repudiation section.

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/740.html" title="Last updated on May 22, 2021, 3:04 PM UTC (a31e6d3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/740/ab18a18...a31e6d3.html" title="Last updated on May 22, 2021, 3:04 PM UTC (a31e6d3)">Diff</a>
> Update Key and Signature Expiration section.

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/745.html" title="Last updated on May 29, 2021, 6:53 PM UTC (4be0942)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/745/435a304...4be0942.html" title="Last updated on May 29, 2021, 6:53 PM UTC (4be0942)">Diff</a>
> Fix editorial issues with Enhanced URNs section.

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/746.html" title="Last updated on May 29, 2021, 6:58 PM UTC (2d237be)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/746/435a304...2d237be.html" title="Last updated on May 29, 2021, 6:58 PM UTC (2d237be)">Diff</a>
> Update Immutability section in Security Considerations.

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/747.html" title="Last updated on May 29, 2021, 7:01 PM UTC (217bd25)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/747/435a304...217bd25.html" title="Last updated on May 29, 2021, 7:01 PM UTC (217bd25)">Diff</a>
> Update Encrypted Data section in Security Considerations.

- index.html
Addresses: #734
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/748.html" title="Last updated on May 25, 2021, 10:47 PM UTC (242ea30)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/748/435a304...242ea30.html" title="Last updated on May 25, 2021, 10:47 PM UTC (242ea30)">Diff</a>
> Update DID Document examples

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/750.html" title="Last updated on May 23, 2021, 11:47 PM UTC (9ffd9bc)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/750/435a304...9ffd9bc.html" title="Last updated on May 23, 2021, 11:47 PM UTC (9ffd9bc)">Diff</a>
> Fix editorial issues with content integrity protection.

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/751.html" title="Last updated on May 30, 2021, 3:08 PM UTC (37402f8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/751/435a304...37402f8.html" title="Last updated on May 30, 2021, 3:08 PM UTC (37402f8)">Diff</a>
> Fix editorial issues with persistence section.

- index.html
Signed-off-by: Drummond Reed <drummond@connect.me>
Addresses issue #719
***
<a href="https://pr-preview.s3.amazonaws.com/talltree/did-core/pull/754.html" title="Last updated on Jun 8, 2021, 12:54 AM UTC (741824f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/754/435a304...talltree:741824f.html" title="Last updated on Jun 8, 2021, 12:54 AM UTC (741824f)">Diff</a>
> add appendix text RE change in controller

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/758.html" title="Last updated on Jun 8, 2021, 12:58 AM UTC (8076bfb)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/758/93b0b06...8076bfb.html" title="Last updated on Jun 8, 2021, 12:58 AM UTC (8076bfb)">Diff</a>
> Fix editorial issues with Privacy Considerations intro.

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/760.html" title="Last updated on Jun 8, 2021, 1:01 AM UTC (c985dc4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/760/93b0b06...c985dc4.html" title="Last updated on Jun 8, 2021, 1:01 AM UTC (c985dc4)">Diff</a>
> Editorial fixes to DID Correlation Risks section.

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/762.html" title="Last updated on May 30, 2021, 8:53 PM UTC (b6f733a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/762/93b0b06...b6f733a.html" title="Last updated on May 30, 2021, 8:53 PM UTC (b6f733a)">Diff</a>
> Update editorial issues with DID Subject Classification section.

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/763.html" title="Last updated on Jun 9, 2021, 12:32 AM UTC (3df3447)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/763/93b0b06...3df3447.html" title="Last updated on Jun 9, 2021, 12:32 AM UTC (3df3447)">Diff</a>
> Fix editorial issues in Service Privacy section.

- index.html
This PR removes at risk issue markers for features that have received enough implementations AND this PR presumes the WG will approve the following resolutions:
https://lists.w3.org/Archives/Public/public-did-wg/2021Jul/0004.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/775.html" title="Last updated on Jul 11, 2021, 7:08 PM UTC (427eead)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/775/b57167a...427eead.html" title="Last updated on Jul 11, 2021, 7:08 PM UTC (427eead)">Diff</a>
> Remove at risk issue markers that have enough implementation support.

- index.html
The PR fixes #794 
It makes the edits mentioned in the issue.
Signed-off-by: Brent Zundel <brent.zundel@gmail.com>
***
<a href="https://pr-preview.s3.amazonaws.com/brentzundel/did-spec/pull/795.html" title="Last updated on Sep 7, 2021, 4:02 PM UTC (f586a12)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/795/c672e55...brentzundel:f586a12.html" title="Last updated on Sep 7, 2021, 4:02 PM UTC (f586a12)">Diff</a>
> Edit figure 9 and 10 description text

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/801.html" title="Last updated on Oct 25, 2021, 1:57 PM UTC (d4709d8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/801/d20b7c7...d4709d8.html" title="Last updated on Oct 25, 2021, 1:57 PM UTC (d4709d8)">Diff</a>
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/801.html" title="Last updated on Jan 6, 2022, 8:05 AM UTC (d4709d8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/801/d20b7c7...d4709d8.html" title="Last updated on Jan 6, 2022, 8:05 AM UTC (d4709d8)">Diff</a>
> Add id properties to example did documents

- index.html
Closes #806
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/809.html" title="Last updated on Dec 13, 2021, 11:06 PM UTC (ab7ef21)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/809/d20b7c7...ab7ef21.html" title="Last updated on Dec 13, 2021, 11:06 PM UTC (ab7ef21)">Diff</a>
> add editorial clarification for controller and VM semantics

- index.html
This addresses #870.
I largely used the proposed text from that issue, but rewrote the first sentence. It could probably use some wordsmithing.
Also I wasn't sure on the title. Audience, Intended Audience, Target Audience?
***
<a href="https://pr-preview.s3.amazonaws.com/wip-abramson/did-core/pull/876.html" title="Last updated on Jan 7, 2025, 1:04 PM UTC (2bf8d92)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/876/3fa1d8d...wip-abramson:2bf8d92.html" title="Last updated on Jan 7, 2025, 1:04 PM UTC (2bf8d92)">Diff</a>
> Add audience section to the spec
