index.html

Add initial content to the data model section on DID Documents.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-spec/pull/30.html" title="Last updated on Oct 10, 2019, 1:07 AM UTC (68cc190)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-spec/30/3df087e...68cc190.html" title="Last updated on Oct 10, 2019, 1:07 AM UTC (68cc190)">Diff</a>

Add initial text to DID Document section.

---

index.html

Fixes #47 (see discussion there).
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-spec/pull/66.html" title="Last updated on Oct 18, 2019, 10:17 PM UTC (99d9e76)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-spec/66/ee57740...99d9e76.html" title="Last updated on Oct 18, 2019, 10:17 PM UTC (99d9e76)">Diff</a>

Make "id" optional for services and public keys.

---

terms.html

To be consistent with f87f7ed71b9f99cf7ac7ecfaf2e5ec190fb76a7c.

Fix grammar in DID path and fragment sentence.

---

index.html

- Added the `w3cid` entry for each editor and author (this is required by Echidna)
- Added the `wg` and `wgURI` fields (necessary for the respec boilerplate, see https://github.com/w3c/did-spec/pull/87#issuecomment-545344978)
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-spec/pull/89.html" title="Last updated on Oct 23, 2019, 10:17 AM UTC (84ecb95)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-spec/89/b1d8c84...84ecb95.html" title="Last updated on Oct 23, 2019, 10:17 AM UTC (84ecb95)">Diff</a>

Admin changes in the respec setting

---

index.html

Solves most of #48, and should close #38 and #40.
***
<a href="https://pr-preview.s3.amazonaws.com/rhiaro/did-spec/pull/86.html" title="Last updated on Oct 26, 2019, 6:39 PM UTC (ee4c5e8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-spec/86/99a0873...rhiaro:ee4c5e8.html" title="Last updated on Oct 26, 2019, 6:39 PM UTC (ee4c5e8)">Diff</a>

Editorial updates

---

README.md

The "read directly" link is broken.

Fixed hyperlink

---

FPWD/2019-11-07/index.html
index.html

On the 2019-11-05 call it was resolved to use `https://www.w3.org/ns/did/v1` as the @context URI.
See also #5
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/96.html" title="Last updated on Nov 5, 2019, 5:59 PM UTC (92c7b10)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/96/d612653...92c7b10.html" title="Last updated on Nov 5, 2019, 5:59 PM UTC (92c7b10)">Diff</a>

Update @context URI

---

index.html

Removed some redundant language and consistently structured DID documents and DID methods sections. Also a few untestable normative statements in there have been rephrased or removed.
Removed (rephrased) some normative language in Security and Privacy considerations sections.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/108.html" title="Last updated on Nov 25, 2019, 4:10 PM UTC (ed39181)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/108/a8d0c28...ed39181.html" title="Last updated on Nov 25, 2019, 4:10 PM UTC (ed39181)">Diff</a>

Editorial pass through latter half

---

index.html

Some wording changes, some punctuation, spacing, and line length updates.
***
<a href="https://pr-preview.s3.amazonaws.com/grantnoble/did-core/pull/111.html" title="Last updated on Nov 18, 2019, 12:06 PM UTC (c27ba74)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/111/a8d0c28...grantnoble:c27ba74.html" title="Last updated on Nov 18, 2019, 12:06 PM UTC (c27ba74)">Diff</a>

Intro editorial review

---

index.html
terms.html

Wording and grammar changes, some additions to the data-lt attributes (or removed it if blank), rearranged the list in alphabetical order, anchor tags around terms that should be linked, and line space updates. In terms.html, where I changed the data-lt attribute from "DID controller(s)" to "DID controllers", I made corresponding changes in index.html.
***
<a href="https://pr-preview.s3.amazonaws.com/grantnoble/did-core/pull/113.html" title="Last updated on Nov 26, 2019, 3:31 AM UTC (ed37745)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/113/979bfe3...grantnoble:ed37745.html" title="Last updated on Nov 26, 2019, 3:31 AM UTC (ed37745)">Diff</a>

Terminology section editorial updates

---

index.html

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/109.html" title="Last updated on Dec 6, 2019, 3:45 PM UTC (553639d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/109/12f2ca3...553639d.html" title="Last updated on Dec 6, 2019, 3:45 PM UTC (553639d)">Diff</a>

Add key expression formats for secp256r1.

---

index.html

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/102.html" title="Last updated on Dec 6, 2019, 3:47 PM UTC (493b8ed)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/102/943db24...493b8ed.html" title="Last updated on Dec 6, 2019, 3:47 PM UTC (493b8ed)">Diff</a>

Add key expression formats for ed25519.

---

common.js
index.html

This PR attempts to partially resolve issue #67 by stating that public key formats will be limited. It also adds a suggestion for how RSA keys are expressed.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/100.html" title="Last updated on Dec 10, 2019, 7:53 PM UTC (5287f42)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/100/02b8613...5287f42.html" title="Last updated on Dec 10, 2019, 7:53 PM UTC (5287f42)">Diff</a>

Add public key value expression goals. Add key expression formats for RSA, secp256k1, secp256r1, ed25519, and curve25519.

---

index.html

In order to further discuss DID parameters (aka matrix parameters), it has been requested that we add text to clarify when to use them and when not to use them.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/144.html" title="Last updated on Dec 17, 2019, 2:49 PM UTC (f50e05b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/144/26f4891...f50e05b.html" title="Last updated on Dec 17, 2019, 2:49 PM UTC (f50e05b)">Diff</a>

Clarify when DID parameters should (not) be used.

---

index.html

Identical changes to https://github.com/w3c/did-core/pull/112 but with a clean history.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/130.html" title="Last updated on Jan 21, 2020, 2:49 PM UTC (9fabb41)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/130/e479550...9fabb41.html" title="Last updated on Jan 21, 2020, 2:49 PM UTC (9fabb41)">Diff</a>

Move DID method security & privacy into normative section

---

index.html
terms.html

Mostly by pulling @dlongley's words from various places around the web :)
This is a first pass at sorting out a lot of uses of 'controller' and should fix the problems with the authentication section. I also updated the definition of 'controller', and added definitions for 'proof purpose' and 'verification method'. It contains new or changed normative language. Needs careful review please! Anticipating changes and corrections.
The Authorization & Delegation section still contains old language still that I'm not sure about.
The Binding of Identity section in Security Considerations is I think also wrong, but I haven't tried to do anything with that yet.
When complete, should fix #2, #3, #22, #39 and help with #4.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/123.html" …

Rewrite authentication section

---

index.html

Removes old text from the NOTE at the start of Security Considerations, that no longer makes sense in context.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/155.html" title="Last updated on Jan 25, 2020, 10:12 AM UTC (48ac11c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/155/bee98cb...48ac11c.html" title="Last updated on Jan 25, 2020, 10:12 AM UTC (48ac11c)">Diff</a>

Cut down security note; fixes #115

---

terms.html

This is an attempt to define the "DID delegate" term and remove the old definitions for "delegate" and "dependent", which were not used in the specification.

Add DID Delegate terminology. Remove delegate/dependent. Fix #4.

---

index.html

This section adds an IANA considerations section, which we need to do in time... but it's being added so we can establish MIME Types for DID Documents, which then describe how fragment identifiers should be interpreted by pointing to the Fragment section in the spec. Doing so will address issue #1.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/196.html" title="Last updated on Feb 21, 2020, 2:14 AM UTC (5741e22)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/196/3fb8902...5741e22.html" title="Last updated on Feb 21, 2020, 2:14 AM UTC (5741e22)">Diff</a>

Add IANA Considerations section. Fix #1.

---

index.html

This PR attempts to address issue #80 raised by @peacekeeper by adding the conformance classes contemplated by the specification. It is the first part of addressing @jricher's request in this week's DID WG meeting.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/191.html" title="Last updated on Feb 21, 2020, 2:45 AM UTC (7f46a0b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/191/1b935d8...7f46a0b.html" title="Last updated on Feb 21, 2020, 2:45 AM UTC (7f46a0b)">Diff</a>

Define all conformance classes. Fix #80.

---

index.html

This is a reorganization of section 5 on DID and DID URLs. It follows the approach described in https://github.com/w3c/did-core/issues/183#issuecomment-587018974.
Note that this PR does _**not**_ (yet) changes the term "DID URL" to "DID Locator": I am not sure there is a consensus on that. I am happy to do that change if there is a consensus or, alternatively, do that in a separate PR at a later time.
PR mentions #183
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/212.html" title="Last updated on Mar 3, 2020, 4:33 PM UTC (9c6b361)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/212/90c68be...9c6b361.html" title="Last updated on Mar 3, 2020, 4:33 PM UTC (9c6b361)">Diff</a>

Reorganisation of section 5

---

index.html

Made a mistake in #212, as pointed out by @peacekeeper in https://github.com/w3c/did-core/pull/212#issuecomment-595177574: a section got lost in the reorg. Have put it back.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/214.html" title="Last updated on Mar 5, 2020, 11:56 AM UTC (95afb99)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/214/04a2202...95afb99.html" title="Last updated on Mar 5, 2020, 11:56 AM UTC (95afb99)">Diff</a>

Added a (forgotten) section, amending the latest section 5 reorg

---

index.html

Addresses #34
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/216.html" title="Last updated on Mar 5, 2020, 1:00 PM UTC (e26affd)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/216/ad87e73...e26affd.html" title="Last updated on Mar 5, 2020, 1:00 PM UTC (e26affd)">Diff</a>

Disallow empty method-specific-id in ABNF.

---

index.html

Fixes a broken link for issue: https://github.com/w3c/did-core/issues/181
***
<a href="https://pr-preview.s3.amazonaws.com/yancyribbens/did-core/pull/227.html" title="Last updated on Mar 17, 2020, 4:01 PM UTC (a57ed45)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/227/93bc34c...yancyribbens:a57ed45.html" title="Last updated on Mar 17, 2020, 4:01 PM UTC (a57ed45)">Diff</a>

Update broken URL for BIP113

---

index.html

In issue #180 there was a concern raised that the example provided
is confusing. In this pull request the example was changed to use a
more common method of indicating revocation which aligns with section
7.3 of the specification.
Closes #180
***
<a href="https://pr-preview.s3.amazonaws.com/kdenhartog/did-core/pull/230.html" title="Last updated on Mar 19, 2020, 1:45 AM UTC (bb2ec1b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/230/93bc34c...kdenhartog:bb2ec1b.html" title="Last updated on Mar 19, 2020, 1:45 AM UTC (bb2ec1b)">Diff</a>

change example of a revoked key to use a more common example

---

index.html

- Add language about what an "Update" is.
Based on feedback here: https://github.com/w3c/did-core/issues/174
***
<a href="https://pr-preview.s3.amazonaws.com/OR13/did-core/pull/220.html" title="Last updated on Mar 21, 2020, 7:09 PM UTC (47382b3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/220/414798f...OR13:47382b3.html" title="Last updated on Mar 21, 2020, 7:09 PM UTC (47382b3)">Diff</a>

Add language regarding DID Method Update Operation

---

index.html

Addresses https://github.com/w3c/did-core/issues/131
- Add note about public key identifiers and compound keys
- Add publicKeyJwk example
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Mar 15, 2020, 6:54 PM UTC)_.
<details>
:rotating_light: [Spec Generator](https://www.w3.org/2015/labs/) - Spec Generator is the web service used to build specs that rely on ReSpec.
:link: [Related URL](https://labs.w3.org/spec-generator/?type=respec&url=https%3A%2F%2Frawcdn.githack.com%2FOR13%2Fdid-core%2F20ae30caf2158026be71d6b45dfc4f362dd53a49%2Findex.html%3FisPreview%3Dtrue)
```
<html><body><h1>504 Gateway Time-out</h1>
The …
```

Add publicKeyJwk with compound key identifier example and note

---

common.js
index.html

This addresses issues #166 by removing the normative statement and
adding a link to the rubrics for developers to reference.
Closes #166
***
<a href="https://pr-preview.s3.amazonaws.com/kdenhartog/did-core/pull/231.html" title="Last updated on Mar 19, 2020, 1:52 AM UTC (0116868)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/231/93bc34c...kdenhartog:0116868.html" title="Last updated on Mar 19, 2020, 1:52 AM UTC (0116868)">Diff</a>

remove untestable normative statement regarding did method specs

---

index.html

***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Mar 31, 2020, 8:40 PM UTC)_.
<details>
:rotating_light: [HTML Diff Service](http://services.w3.org/htmldiff) - The HTML Diff Service is used to create HTML diffs of the spec changes suggested in a pull request.
:link: [Related URL](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fpr-preview.s3.amazonaws.com%2Fw3c%2Fdid-core%2Fpull%2F246%2Fb5d617c.html&doc2=https%3A%2F%2Fpr-preview.s3.amazonaws.com%2Fw3c%2Fdid-core%2Fpull%2F246.html)
```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html …
```

Remove reference to closed issue #35.

---

index.html

***
<a href="https://pr-preview.s3.amazonaws.com/PeterTheOne/did-core/pull/251.html" title="Last updated on Apr 3, 2020, 4:18 PM UTC (095f41e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/251/1812b11...PeterTheOne:095f41e.html" title="Last updated on Apr 3, 2020, 4:18 PM UTC (095f41e)">Diff</a>

Fix typo: duplicate "are"

---

index.html

I don't see the point of a section that references itself in the second paragraph of itself.
As an alternative it could say something in the line of `For more information, keep reading.`.
***
<a href="https://pr-preview.s3.amazonaws.com/PeterTheOne/did-core/pull/250.html" title="Last updated on Apr 3, 2020, 2:56 PM UTC (60e4ffe)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/250/eb4c6fa...PeterTheOne:60e4ffe.html" title="Last updated on Apr 3, 2020, 2:56 PM UTC (60e4ffe)">Diff</a>

Remove self-reference to the public keys section

---

index.html

I did a pass to make sure all references to draft/unofficial documents in normative sections show up as informative references, per #53
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/245.html" title="Last updated on Mar 31, 2020, 9:46 AM UTC (f3e1d07)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/245/b5d617c...f3e1d07.html" title="Last updated on Mar 31, 2020, 9:46 AM UTC (f3e1d07)">Diff</a>

Fix references that should be non-normative

---

index.html

Very small update to JSON-LD requirements to say the value of `id` must always be a DID, even though JSON-LD permits any kind of IRI; see #217
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/242.html" title="Last updated on Apr 8, 2020, 11:20 AM UTC (437cbb1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/242/fd4c5cf...437cbb1.html" title="Last updated on Apr 8, 2020, 11:20 AM UTC (437cbb1)">Diff</a>

Clarify id value for json-ld

---

index.html

I removed the non-normative suggestion to self-monitor (poll) for changes to DID docs, as proposed in #179. I reworded the section a bit to make stripping a bullet out of a short list less odd. (The bullets are gone, it's just paragraphs now.) 
I'm not sure if there's consensus to remove this wording though - so far nobody objected in the issue, so anyone who really wants to keep it should comment.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/244.html" title="Last updated on Mar 30, 2020, 12:25 PM UTC (780b7dd)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/244/fd4c5cf...780b7dd.html" title="Last updated on Mar 30, 2020, 12:25 PM UTC (780b7dd)">Diff</a>

Remove suggestion of polling

---

index.html
terms.html

There is a strange statement about JSON Pointers from way back in the day. Based on where the matrix parameters and DID path discussion is going, JSON Pointer is going to be incompatible. This PR removes JSON Pointer because:
1) No known production-bound implementation depends on it, and 
2) the '/' character is going to be reserved shortly and shouldn't be used.
Related to #164.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/257.html" title="Last updated on May 1, 2020, 4:35 PM UTC (af251b6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/257/aaac504...af251b6.html" title="Last updated on May 1, 2020, 4:35 PM UTC (af251b6)">Diff</a>

Remove statement about JSON Pointer.

---

index.html

Fixes #160
***
<a href="https://pr-preview.s3.amazonaws.com/selfissued/did-core/pull/277.html" title="Last updated on May 16, 2020, 5:35 PM UTC (700f4e3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/277/48bc712...selfissued:700f4e3.html" title="Last updated on May 16, 2020, 5:35 PM UTC (700f4e3)">Diff</a>

Accurately describe dependence on registries

---

terms.html

Signed-off-by: Daniel Hardman <daniel.hardman@gmail.com>
See https://github.com/w3c/did-core/issues/276

Amplify/broaden def of 'verification method'

---

index.html

The reference to DID-RESOLUTION in line 1006 was only in single square brackets, not double. So this PR just doubles up those [] characters.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/287.html" title="Last updated on May 18, 2020, 8:08 AM UTC (ea6dc25)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/287/9a7cad0...ea6dc25.html" title="Last updated on May 18, 2020, 8:08 AM UTC (ea6dc25)">Diff</a>

Trivial nit wrt a reference

---

index.html

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/285.html" title="Last updated on May 14, 2020, 8:10 PM UTC (a5f81c6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/285/48bc712...a5f81c6.html" title="Last updated on May 14, 2020, 8:10 PM UTC (a5f81c6)">Diff</a>

Remove matrix parameters, addresses #159.

---

index.html
terms.html

Consensus in #162 that "DID Registry" is bad, so changing it throughout to "Verifiable data registry" until, if ever, a better term is found.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/302.html" title="Last updated on May 31, 2020, 6:59 AM UTC (5c68289)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/302/490cccb...5c68289.html" title="Last updated on May 31, 2020, 6:59 AM UTC (5c68289)">Diff</a>

Change 'DID registry' to 'Verifiable data registry', towards #162

---

common.js
index.html

Resolves #169
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/303.html" title="Last updated on May 31, 2020, 7:44 AM UTC (3d213bd)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/303/490cccb...3d213bd.html" title="Last updated on May 31, 2020, 7:44 AM UTC (3d213bd)">Diff</a>

Replace links to external registries with the DID Spec Registries

---

index.html

Replaced with `Ed25519VerificationKey2018` examples. Should close issues #9 and #10.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/307.html" title="Last updated on Jun 1, 2020, 6:45 PM UTC (db1a03a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/307/490cccb...db1a03a.html" title="Last updated on Jun 1, 2020, 6:45 PM UTC (db1a03a)">Diff</a>

Replace RsaVerificationKey2018 examples

---

index.html
terms.html

Adds verificationMethod as a DID document property, fixing #283. 
Also removes undefined terms that are verification relationships - which fixes #272 - replacing them with links to the DID Spec Registries, until such a time as (if ever) they are defined as top level properties in DID Core.
**WIP!** Needs input:
* The contents of the verificationMethod example please, it's blank right now.
* I essentially copied the definitions for the property from publicKey. I also created a "verification relationships" subsection to express some of what was in a NOTE in the publicKey section. I'd appreciate close review and corrections to this because I'm not sure if it's all accurate.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/304.html" title="Last updated on Jun 5, 2020, 5:09 …

Add verificationMethod as a DID document property.

---

index.html

During the various discussions around matrix vs. query parameter syntax, it was mentioned that while there are a lot of examples of [Method-Specific DID URL Parameters](https://w3c.github.io/did-core/#method-specific-did-url-parameters), there are currently no examples of [Generic DID URL Parameters](https://w3c.github.io/did-core/#generic-did-url-parameters). This PR adds two such examples.
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Jun 1, 2020, 2:08 PM UTC)_.
<details>
:rotating_light: [Spec Generator](https://www.w3.org/2015/labs/) - Spec Generator is the web service used to build specs that rely on …

Add DID parameter examples.

---

index.html

This adapts the DID Resolution functional definition defined by #253 into a single typed function with requirements for the function signature and implementation conformance. 
This builds on #295.
***
<a href="https://pr-preview.s3.amazonaws.com/jricher/did-core/pull/296.html" title="Last updated on Jun 9, 2020, 4:23 PM UTC (38c9969)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/296/200cff0...jricher:38c9969.html" title="Last updated on Jun 9, 2020, 4:23 PM UTC (38c9969)">Diff</a>

Define resolution function with data types

---

index.html

This PR is to clarify the combination of timestamp and signatures in response to https://github.com/w3c/did-core/issues/178.
***
<a href="https://pr-preview.s3.amazonaws.com/yancyribbens/did-core/pull/309.html" title="Last updated on Jun 10, 2020, 5:48 AM UTC (2b14202)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/309/93bc34c...yancyribbens:2b14202.html" title="Last updated on Jun 10, 2020, 5:48 AM UTC (2b14202)">Diff</a>

clarify use practice of using a timestamp with signatures

---

index.html

This PR moves the Future Work section to the implementation guide. All text has been migrated here: 
https://w3c.github.io/did-imp-guide/#future-work

Move Future Work section to implementation guide.

---

index.html

Remove the interop registries appendix as we refer to the registries throughout the document now and the appendix duplicates content earlier in the specification as well as in the section on interop.

Remove interop registries appendix.

---

index.html

per #204.
(Also fixes spacing and markup in CBOR section.)

Makes use of property/name/value consistent

---

index.html
terms.html

Also replaces references to 'this specification' in the terms file with 'the DID Core specification' (and a link), for when the terms file is included elsewhere (ie. use cases).
Fixes #311.

Put all term dfns in terms.html

---

index.html

Replaces https://github.com/w3c/did-core/pull/322 and https://github.com/w3c/did-core/pull/323. Builds on https://github.com/w3c/did-core/pull/296 and https://github.com/w3c/did-core/pull/297.
During the [2020-06-18 DID WG Topical Call on DID Resolution contracts](https://www.w3.org/2019/did-wg/Meetings/Minutes/2020-06-18-did-topic) we had consensus that we should have two abstract functions for DID resolutions - one called `resolve` that returns a DID document as the abstract data model, and one called `resolveStream` that returns a DID document as a byte stream in one of the conformant representations.
After merging this, we can add a few remaining improvements that have been discussed, such as compatibility with the [Infra standard](https://infra.spec.whatwg.org/), and definition of …

Support resolve() and resolveStream() functions

---

index.html

Issue #122 has a lot of back-and-forth about the relationship between the `controller` property and the actual DID controller, aka the entity that can edit the DID document. 
The original issue was about whether we can assume the DID subject (aka an entity that can authenticate itself with verification material contained in the DID doc.. I think?) is default controller in the absence of a `controller` property. (Short answer to that being 'no'.)
I'm not sure there's consensus, so I've added a NOTE presenting one set of perspectives from that thread, which is basically that the `controller` property is indicative but ultimately who/what can or cannot edit a DID doc, and under what circumstances, is up to the DID method, `controller` property or no.
I'm not sure if there's normative …

Relationship between `controller` property and DID controller

---

index.html

See https://github.com/w3c/did-core/issues/333
***
<a href="https://pr-preview.s3.amazonaws.com/Crenshinibon/did-core/pull/334.html" title="Last updated on Jun 25, 2020, 12:23 PM UTC (445af8e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/334/515db7b...Crenshinibon:445af8e.html" title="Last updated on Jun 25, 2020, 12:23 PM UTC (445af8e)">Diff</a>

Fixed ABNF for method-specific-id of DID Syntax

---

ECHIDNA

The reference to the diagram was missing, as reported in 
https://lists.w3.org/Archives/Public/public-did-wg/2020Jul/0009.html

Added missing reference to the diagram in ECHIDNA

---

terms.html

Signed-off-by: Drummond Reed <drummond@connect.me>
***
<a href="https://pr-preview.s3.amazonaws.com/talltree/did-core/pull/335.html" title="Last updated on Jul 13, 2020, 2:16 PM UTC (5fc536c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/335/1443c56...talltree:5fc536c.html" title="Last updated on Jul 13, 2020, 2:16 PM UTC (5fc536c)">Diff</a>

full editing pass on all terms

---

index.html

This PR updates the specification to use the INFRA specification https://infra.spec.whatwg.org/ in an attempt to formalize the abstract data model and concrete representations of that abstract data model.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/342.html" title="Last updated on Jul 14, 2020, 12:02 AM UTC (1664a6f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/342/9d8e245...1664a6f.html" title="Last updated on Jul 14, 2020, 12:02 AM UTC (1664a6f)">Diff</a>

[WIP] Update specification to use INFRA

---

index.html

> @peacekeeper  wrote: this is a remnant of the version of the spec that had matrix parameters. I think the sentence should simply be removed.
fixes #353
***
<a href="https://pr-preview.s3.amazonaws.com/Fak3/did-core/pull/354.html" title="Last updated on Jul 22, 2020, 1:13 PM UTC (5ee6aba)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/354/78f1148...Fak3:5ee6aba.html" title="Last updated on Jul 22, 2020, 1:13 PM UTC (5ee6aba)">Diff</a>

Remove obsolete sentence

---

index.html

This PR attempts to write some base text for the metadata section based on infra data structures. It attempts to strike the right balance by strongly suggesting that string-string values should be used. However, if non-string values are required, then infra types that are loss-lessly expressible across all representations must be used. Hopefully this strikes the right compromise.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/347.html" title="Last updated on Jul 28, 2020, 1:16 PM UTC (64e5f41)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/347/78f1148...64e5f41.html" title="Last updated on Jul 28, 2020, 1:16 PM UTC (64e5f41)">Diff</a>

Add Metadata section based on infra data structures.

---

index.html

In line with the WG's [resolution on 2020-06-30](https://www.w3.org/2019/did-wg/Meetings/Minutes/2020-06-30-did#resolution1), this minimal PR swaps the 3 instances of 'replying party' for 'requesting party'. If merged, Issue #248 can be closed. The closely related issue in the Use Cases document, ([issue 39](https://github.com/w3c/did-use-cases/issues/39) in that repo) has been closed and the UCR now consistently refers to requesting parties (actually, it refers to Requesting Parties, with upper case R and P, which is a difference from the core spec but probably not something to worry about too much).
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/350.html" title="Last updated on Jul 16, 2020, 10:48 AM UTC (3a27e63)">Preview</a> | <a …

Swap relying party for requesting party Will fix #248

---

index.html

Adjusts the nesting a bit and some of the subheadings for readability.
Adds a mini TOC to the beginning so that people looking for actual property names can find them quickly (as it's not always obvious from the subheadings in the actual TOC).
Adds <code>dfn</code> elements to all the properties, and corresponding internal refs. Also includes some CSS so links in code elements keep the same appearance.
Removes the `publicKey` property, and integrates remaining text into the Verification Methods section. Adds a subsection for key types and formats. I'd appreciate careful review of this in particular to make sure I didn't mix up wording around keys vs verification methods. I also add explicit values for `type` for each of the keys (where known; one is missing). I'm aware that support for …

Restructure Core Properties section

---

index.html

This fixes https://github.com/w3c/did-core/issues/349
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/357.html" title="Last updated on Jul 29, 2020, 8:53 AM UTC (73e89f7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/357/6988450...73e89f7.html" title="Last updated on Jul 29, 2020, 8:53 AM UTC (73e89f7)">Diff</a>

Add 'relative-ref' DID URL parameter. Fixes #349.

---

index.html

- Use `query` from RFC3986 (URI) instead of parsing param names and values
- Correct RFC5324 (MIB for Fibre-Channel Security) to RFC5234 (ABNF)
See discussion here for reasoning:
https://github.com/w3c/did-core/issues/344
***
<a href="https://pr-preview.s3.amazonaws.com/wyc/did-core/pull/360.html" title="Last updated on Jul 28, 2020, 10:29 PM UTC (2353f5d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/360/2956430...wyc:2353f5d.html" title="Last updated on Jul 28, 2020, 10:29 PM UTC (2353f5d)">Diff</a>

Simplify DID URL ABNF

---

index.html

Addresses #203 and #174.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/365.html" title="Last updated on Aug 10, 2020, 1:59 PM UTC (6663b38)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/365/3cc2641...6663b38.html" title="Last updated on Aug 10, 2020, 1:59 PM UTC (6663b38)">Diff</a>

Move "created" and "updated" from Core Properties to DID document metadata

---

index.html

While fixing the language around contexts, I noticed what I believe to be an erroneous comment regarding the value of `id` that states it *must* be a DID. However, this is *only* true when referring to the DID subject. The value of `id` of a service endpoint or verification method, for example, is not a DID.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/362.html" title="Last updated on Sep 1, 2020, 7:48 PM UTC (bf5a714)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/362/ce2f9a9...bf5a714.html" title="Last updated on Sep 1, 2020, 7:48 PM UTC (bf5a714)">Diff</a>

Update context requirements for JSON-LD producers/consumers.

---

index.html

Adds the reqlist respec extension to list normative statements in a sidebar. ~~Leaving this PR here and will keep it up to date with the main branch so we can use the preview for reference for the test suite etc.~~ [preview here](https://holosuite.rhiaro.co.uk/did-core-reqlist/#list-of-requirements) (PR preview only shows the static HTML version with the JS).
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/372.html" title="Last updated on Sep 3, 2020, 3:05 PM UTC (2bfca41)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/372/5d5e992...2bfca41.html" title="Last updated on Sep 3, 2020, 3:05 PM UTC (2bfca41)">Diff</a>

Add reqlist JS for listing normative statements

---

index.html

I think section 1.1 has a typo where it says that `did` is the scheme - surely that should be URI?
This PR changes that single character (from L to I)
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/351.html" title="Last updated on Jul 16, 2020, 11:40 AM UTC (adfc367)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/351/78f1148...adfc367.html" title="Last updated on Jul 16, 2020, 11:40 AM UTC (adfc367)">Diff</a>

URI not URL in section 1.1

---

index.html

following feedback from @dlongley and @jandrieu in #122
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/371.html" title="Last updated on Aug 31, 2020, 6:46 PM UTC (330a828)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/371/ce2f9a9...330a828.html" title="Last updated on Aug 31, 2020, 6:46 PM UTC (330a828)">Diff</a>

Update note about controller value 

---

index.html

This PR does the following:
- Remove method-specific DID parameters. Addresses https://github.com/w3c/did-core/issues/36
- Mark 'hl' DID parameter as non-normative. Addresses https://github.com/w3c/did-core/issues/137.
- Some minor editorial changes to DID Parameters section.
- Add paragraph on using the DID Spec Registries for DID parameters. See this comment https://github.com/w3c/did-core/issues/36#issuecomment-648468519.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/378.html" title="Last updated on Aug 26, 2020, 1:22 PM UTC (b9715e2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/378/8c47db8...b9715e2.html" title="Last updated on Aug 26, 2020, 1:22 PM UTC (b9715e2)">Diff</a>

Remove method-specific DID parameters

---

index.html
terms.html

Fixes the markup error that was causing ECHIDNA to fail.
Also disambiguates definitions for controller, authentication and service, as they were duplicated by their respective property definitions. There should be no respec errors on this now.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/383.html" title="Last updated on Aug 31, 2020, 8:20 PM UTC (e6a3732)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/383/ce2f9a9...e6a3732.html" title="Last updated on Aug 31, 2020, 8:20 PM UTC (e6a3732)">Diff</a>

Markup / structural fixes

---

index.html

As per: https://github.com/w3c/did-core/issues/364
- Fill the DID URL Dereferencing section with abstract function, function
parameters, return values, and their definitions, using language and format
consistent to (and drawn from) the DID Resolution section.
- Delegate the handling of DID URLs which are also DIDs to the DID Resolution
process, thereby ensuring that DID URL Dereferencing is a superset of DID
Resolution, just as DID URLs are a superset of DIDs.
***
<a href="https://pr-preview.s3.amazonaws.com/wyc/did-core/pull/381.html" title="Last updated on Sep 8, 2020, 11:38 PM UTC (3ce1d0e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/381/8c47db8...wyc:3ce1d0e.html" title="Last updated on Sep 8, 2020, 11:38 PM UTC (3ce1d0e)">Diff</a>

Fill DID URL Dereferencing Section

---

index.html

I propose to re-add language about colons in DID syntax which was originally added in https://github.com/w3c/did-core/pull/215 but then removed again in https://github.com/w3c/did-core/pull/319.
Also see https://github.com/w3c/did-core/issues/98, https://github.com/w3c/did-core/issues/152 and https://github.com/w3c/did-spec-registries/issues/102 for additional discussion about this.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/387.html" title="Last updated on Sep 3, 2020, 1:28 PM UTC (c87ee3a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/387/5d5e992...c87ee3a.html" title="Last updated on Sep 3, 2020, 1:28 PM UTC (c87ee3a)">Diff</a>

Re-add language about colons in DID syntax

---

index.html

Supersedes https://github.com/w3c/did-core/pull/355
I tried to write the main definition of the property in a generic way that should be acceptable to other communities (ie ActivityPub) who are using this property already. 
There is additional introductory text and a note that are more specific to DIDs.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/389.html" title="Last updated on Sep 8, 2020, 8:51 AM UTC (76c1861)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/389/1547e0a...76c1861.html" title="Last updated on Sep 8, 2020, 8:51 AM UTC (76c1861)">Diff</a>

Define alsoKnownAs property

---

index.html

This specifies the format of the value of the `version-time` [DID parameter](https://w3c.github.io/did-core/#did-parameters).
The format specified in this PR is the same as that of the `created` [DID document metadata property](https://w3c.github.io/did-core/#did-document-metadata-properties).
Addresses https://github.com/w3c/did-core/issues/379.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/392.html" title="Last updated on Sep 8, 2020, 8:07 PM UTC (05a6d6d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/392/faddd51...05a6d6d.html" title="Last updated on Sep 8, 2020, 8:07 PM UTC (05a6d6d)">Diff</a>

Specify format of version-time DID parameter value.

---

index.html

The term "client" is undefined in the DID Core specification, and it is potentially problematic in the context of decentralized technologies.
This is an attempt to replace the term "client" with other, better understood terms, such as [DID controller](https://w3c.github.io/did-core/#dfn-did-controllers), [DID resolver](https://w3c.github.io/did-core/#dfn-did-resolvers), and requesting party (see https://github.com/w3c/did-core/pull/350 for more details about the last one).
Addresses https://github.com/w3c/did-core/issues/261.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/393.html" title="Last updated on Sep 8, 2020, 9:29 PM UTC (ffb51cd)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/393/faddd51...ffb51cd.html" title="Last updated on Sep 8, …

Replace "client" with more appropriate terms

---

index.html

This is just a small formatting idea which I mentioned in https://github.com/w3c/did-core/pull/389#pullrequestreview-484539080.
Right now, all the [Core Properties](https://w3c.github.io/did-core/#core-properties) have their own (sub-)section, except for the new `alsoKnownAs`. The PR simply creates a subsection for this property as well.
I don't feel strongly about it, feel free to simply upvote or downvote..
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/397.html" title="Last updated on Sep 17, 2020, 10:24 AM UTC (a247c30)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/397/fbff723...a247c30.html" title="Last updated on Sep 17, 2020, 10:24 AM UTC (a247c30)">Diff</a>

Make alsoKnownAs a subsection of DID Subject.

---

index.html

respec `group` property automatically fetches the correct patent policy from the W3C API. `wgPatentURI` is deprecated. This fixes current ECHIDNA failure.
(Also fixed a couple of internal ref bugs)
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/412.html" title="Last updated on Sep 21, 2020, 11:12 AM UTC (33df8fa)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/412/14b5eda...33df8fa.html" title="Last updated on Sep 21, 2020, 11:12 AM UTC (33df8fa)">Diff</a>

respec: replace WG info with 'group' property and fix internal refs

---

index.html

addresses https://github.com/w3c/did-core/issues/405
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/406.html" title="Last updated on Sep 20, 2020, 3:50 PM UTC (602e2f0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/406/fbff723...602e2f0.html" title="Last updated on Sep 20, 2020, 3:50 PM UTC (602e2f0)">Diff</a>

Add JsonWebKey2020  (JWK) key representation to did core.

---

index.html

Attempt to address https://github.com/w3c/did-core/issues/400
Representations other than JSON-LD, rely on this specification entirely to define "dereferencing".
Today, all representations other than JSON-LD are NOT capable of using fragments on DID URLs to identify sub sections of secondary resources. This PR gives them that capability.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/409.html" title="Last updated on Oct 1, 2020, 7:56 PM UTC (d6ae0e3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/409/14b5eda...d6ae0e3.html" title="Last updated on Oct 1, 2020, 7:56 PM UTC (d6ae0e3)">Diff</a>

Allow fragments to be applied to secondary resources

---

index.html

addresses https://github.com/w3c/did-core/issues/405
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/407.html" title="Last updated on Oct 9, 2020, 5:19 PM UTC (5a68b39)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/407/fbff723...5a68b39.html" title="Last updated on Oct 9, 2020, 5:19 PM UTC (5a68b39)">Diff</a>

Cleanup key representations

---

index.html

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/408.html" title="Last updated on Oct 12, 2020, 1:56 PM UTC (de525cd)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/408/1547e0a...de525cd.html" title="Last updated on Oct 12, 2020, 1:56 PM UTC (de525cd)">Diff</a>

Add JSON-LD Producer / Consumer details

---

index.html

In recent conversations it was proposed that the `resolveStream` function should be renamed to resolveRepresentation, since the main difference is that `resolve` returns the DID document's abstract data model, whereas `resolveRepresentation` returns the DID document in one of the conformant representations.
I think this change will have a positive effect on the current discussion around the abstract data model and representations.
E.g. see:
- https://github.com/w3c/did-core/issues/417
- https://www.w3.org/2019/did-wg/Meetings/Minutes/2020-09-29-did-topic
- https://github.com/w3c-ccg/did-resolution/issues/57
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/424.html" title="Last updated on Oct 2, 2020, 11:58 PM UTC (8876bd5)">Preview</a> | <a …

Rename resolveStream to resolveRepresentation

---

index.html

8.2.3 DID URL Dereferencing Metadata Properties was there twice.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/428.html" title="Last updated on Oct 3, 2020, 7:06 PM UTC (dc6b222)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/428/e03c728...dc6b222.html" title="Last updated on Oct 3, 2020, 7:06 PM UTC (dc6b222)">Diff</a>

editorial: Remove duplicate subsection; fix line lengths

---

index.html

Removes untestable normative language from Conformance section, towards #384
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/426.html" title="Last updated on Oct 18, 2020, 4:00 PM UTC (d3d5772)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/426/c764c67...d3d5772.html" title="Last updated on Oct 18, 2020, 4:00 PM UTC (d3d5772)">Diff</a>

normative statements: Conformance section

---

index.html

Some of the normative statements in the Representations section appear to be saying the same thing twice, in the inverse. I've tried to resolve these to make the more succinct in terms of normative requirements, but maintain most of the original language for clarity. Please let me know if I accidentally removed a distinct normative req though. See: #384
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/434.html" title="Last updated on Oct 18, 2020, 6:18 PM UTC (a680816)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/434/c764c67...a680816.html" title="Last updated on Oct 18, 2020, 6:18 PM UTC (a680816)">Diff</a>

normative statements: Representations section

---

index.html

Removes redundant/untestable intro normative language. Also
makes references to the Registries consistent with the rest
of the spec by saying "SHOULD be registered in" rather than "are
defined in". (#384)
(And fixes spacing / line breaks on several paragraphs)
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/437.html" title="Last updated on Oct 18, 2020, 3:51 PM UTC (4dad60b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/437/c764c67...4dad60b.html" title="Last updated on Oct 18, 2020, 3:51 PM UTC (4dad60b)">Diff</a>

normative statements: Resolution section

---

index.html

Moves normative language about signatures on DID docs (keeping informative guidance) from Security Consideration to Methods section. #384
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/438.html" title="Last updated on Oct 13, 2020, 1:57 PM UTC (fec222f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/438/c764c67...fec222f.html" title="Last updated on Oct 13, 2020, 1:57 PM UTC (fec222f)">Diff</a>

normative statements: Security considerations / methods sections

---

index.html

Some rearranging of normative statements to more appropriate places, and removal where redundant (in intro/advisory sections). More detailed explanations of each in commits. #384
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/436.html" title="Last updated on Oct 18, 2020, 6:21 PM UTC (7ce3feb)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/436/c764c67...7ce3feb.html" title="Last updated on Oct 18, 2020, 6:21 PM UTC (7ce3feb)">Diff</a>

normative statements: JSON and JSON-LD representations sections

---

index.html

Reorganises normative language in Identifier section, towards #384
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/427.html" title="Last updated on Oct 26, 2020, 3:13 PM UTC (47e023a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/427/2a3ca5d...47e023a.html" title="Last updated on Oct 26, 2020, 3:13 PM UTC (47e023a)">Diff</a>

normative statements: Identifier section

---

index.html

Addresses https://github.com/w3c/did-core/issues/402.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/440.html" title="Last updated on Oct 29, 2020, 10:02 PM UTC (ddd8bb5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/440/5dd10b5...ddd8bb5.html" title="Last updated on Oct 29, 2020, 10:02 PM UTC (ddd8bb5)">Diff</a>

Remove "unauthorized" and add "deactivated" error code.

---

index.html

Pointed out by @iherman in #403 this is not a rec-track document, so needs to be an informative rather than normative reference.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/448.html" title="Last updated on Oct 27, 2020, 7:12 PM UTC (7439cd3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/448/5dd10b5...7439cd3.html" title="Last updated on Oct 27, 2020, 7:12 PM UTC (7439cd3)">Diff</a>

references: DID Spec Registries informative

---

index.html

Adds explicitly "at the top level" to statements about the `id` property denoting the DID subject, and a note that clarifies further that `id` may be used on nested objects and does not denote the DID subject in that case. Raised in #401.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/449.html" title="Last updated on Oct 27, 2020, 7:51 PM UTC (b7daf99)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/449/5dd10b5...b7daf99.html" title="Last updated on Oct 27, 2020, 7:51 PM UTC (b7daf99)">Diff</a>

editorial: Clarify that id is only for DID subject when at top level

---

index.html

There was a lot of repetition here, so I've tried to rework the subsections to make it all more succinct. This should not have changed any normative requirement, but close review appreciated in case I missed something. I may have gone overboard with use of NOTE boxes - some of this might be better pulled back out to normal (informative) text after all - let me know what you think.
(Related: comments in #401 and #403 about this section.)
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/451.html" title="Last updated on Nov 4, 2020, 2:44 PM UTC (e73d87a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/451/3151f33...e73d87a.html" title="Last updated on Nov 4, 2020, 2:44 PM UTC (e73d87a)">Diff</a>

Condense Verification Relationships sections

---

index.html
terms.html

This PR implements a number of resolutions made during the last DID WG virtual face-to-face meeting. Namely, it adds different classes of properties, defines all datatypes, and moves representation authoring rules to later in document.
Reviewers should look at the rewritten Data Model section here:
https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/455.html#data-model
and the representation authoring guidelines that was moved here:
https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/455.html#creating-representations
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/455.html" title="Last updated on Nov 17, 2020, 4:49 PM UTC (ecda543)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/455/b426d48...ecda543.html" title="Last updated on Nov 17, …

Rework Data Model section.

---

terms.html

Suggested by @iherman in #401. Obviously not an expert, my understanding is a DLT is kinda shoulda supposed to be immutable but under certain situations this might not technically be the case; but for the purposes of this definition stating it as Ivan suggests I think is probably right. Look, now this comment took longer to write than making the change itself. Just close the PR if it's not appropriate to add "immutable" anyway.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/450.html" title="Last updated on Nov 11, 2020, 2:19 PM UTC (dba8371)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/450/b426d48...dba8371.html" title="Last updated on Nov 11, 2020, 2:19 PM UTC (dba8371)">Diff</a>

terms: add 'immutable' to DLT definition

---

index.html

Adds notes to mark `application/did+ld+json` at risk pending IANA feedback on multiple suffixes issue. See #208
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/458.html" title="Last updated on Nov 16, 2020, 1:14 PM UTC (2845e0c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/458/b426d48...2845e0c.html" title="Last updated on Nov 16, 2020, 1:14 PM UTC (2845e0c)">Diff</a>

Marks did+ld+json media type at risk

---

index.html

Personal preference to remove biometrics examples from the spec. This is too dystopian, and I don't think we should be encouraging it even if it's technically possible. It's also dancing close to the PII and bound-forever problems (even though the example refers to an endpoint, rather than biometric data in the DID doc). I've replaced the example with something less specific about credentials, but also happy to see a better more specific example suggested instead.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/459.html" title="Last updated on Nov 30, 2020, 11:41 AM UTC (9631fd3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/459/b426d48...9631fd3.html" title="Last updated on Nov 30, 2020, 11:41 AM UTC (9631fd3)">Diff</a>

editorial: remove biometrics examples

---

index.html

This is an attempt to address https://github.com/w3c/did-core/issues/390, and to add language about "real-world identity" or "legal identity". This is relevant to the following use cases:
- [Digital Permanent Resident Card](https://w3c.github.io/did-use-cases/#digitalPRC)
- [Public authority identity credentials](https://w3c.github.io/did-use-cases/#publicAuthorityCredentials)
Since this is a privacy-sensitive topic, let's wait for feedback from e.g. @jandrieu , @talltree , @Oskar-van-Deventer , and others.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/466.html" title="Last updated on Nov 24, 2020, 4:58 PM UTC (8479be7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/466/26ad2eb...8479be7.html" title="Last updated on Nov 24, 2020, 4:58 PM UTC …

Add considerations about real-world identity.

---

common.js
index.html

Less of a 'fix' and more of a complete rewrite.
`restrictRefs` is now triggered by `postProcess` in the respec config. It removes any definitions from the terminology section that are not actually used in the spec.
It is not smart enough to detect circular definition cycles within the terminology section itself, but I've eyeballed it and don't think there are any.
There *are* definitions that are *only* referred to from other definitions (and not in the main body of the spec) - but we can't drop these without removing their reference or we get respec errors. Will do another editorial pass over terminology at some point to reduce this.
There's a really hacky bit to stop the invisible 'definition panels' triggering the local-refs-exist linter, because I didn't figure out how to remove the …

respec: fix restrictReferences

---

index.html

This PR builds on top of #455 by adding concrete JSON serialization/deserialization rules for production and consumption. If this PR is acceptable the the group, similar PRs will be raised for the JSON-LD and CBOR sections.
You can preview the changes, which are effectively the addition of conversion tables, here:
JSON Production
https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/469.html#production
JSON Consumption
https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/469.html#consumption
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/469.html" title="Last updated on Nov 24, 2020, 9:59 PM UTC (f8c4ba8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/469/002b9f0...f8c4ba8.html" title="Last updated on Nov 24, 2020, 9:59 PM UTC …

Add concrete serialization rules for JSON based on new data types section.

---

index.html

Rewords normative statement about method names from:
> The authors of a new DID method specification SHOULD use a method name that
> is unique among all DID method names known to them at the time of publication.
to 
> The authors of a new <a>DID method</a> specification are expected to use a
> method name that is unique among all <a>DID method</a> names known to them at
> the time of publication.
because the way it's worded ("known to them") is untestable even by humans.
#384
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/470.html" title="Last updated on Nov 24, 2020, 9:23 PM UTC (142ccad)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/470/002b9f0...142ccad.html" title="Last updated on Nov 24, 2020, 9:23 PM UTC (142ccad)">Diff</a>

methods: remove untestable normative statement

---

index.html

Here's an attempt at getting generic/unknown/syntax-related property representation rules into the spec per the resolutions/discussions this past week.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/454.html" title="Last updated on Dec 1, 2020, 6:25 PM UTC (35e6c03)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/454/b86bed4...35e6c03.html" title="Last updated on Dec 1, 2020, 6:25 PM UTC (35e6c03)">Diff</a>

Add representation language to address syntax and "unknown" properties.

---

index.html

updated CBOR to expand discussion regarding consumption and production.
***
<a href="https://pr-preview.s3.amazonaws.com/jonnycrunch/did-core/pull/420.html" title="Last updated on Dec 1, 2020, 3:58 PM UTC (8bec5aa)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/420/b86bed4...jonnycrunch:8bec5aa.html" title="Last updated on Dec 1, 2020, 3:58 PM UTC (8bec5aa)">Diff</a>

updated cbor section

---

.vscode/settings.json
index.html

Attempt at fixing history in 431.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/473.html" title="Last updated on Dec 6, 2020, 8:43 PM UTC (46532b9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/473/11622f3...46532b9.html" title="Last updated on Dec 6, 2020, 8:43 PM UTC (46532b9)">Diff</a>

Add equivalence properties.

---

index.html

Speaking into the void is never pleasant. There was no comment in response to [my suggested language change in #454](https://github.com/w3c/did-core/pull/454#discussion_r529983390), and it would be lost entirely if I were not saying something now.
To reiterate, I suggested that --
```
Note that no additional processing will be applied to the value of the 
<code>@context</code> object member, if present. The original value will 
be added verbatim to the abstract data model.
```
-- would be clearer than (line breaks added) --
```
Note that the value of the <code>@context</code> object member will be
ignored, if present. That is, this field will not have additional 
processing applied to its value and will be added verbatim to the 
abstract data model.
```
The major reason for this change is …

(editorial) minor language refinement

---

index.html

I think this is simply a mistake.. During the Amsterdam F2F we said that representations may support extension mechanisms that only work in a specific representation, and that can't be losslessly converted to others.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/465.html" title="Last updated on Dec 13, 2020, 8:25 PM UTC (c8fba4b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/465/26ad2eb...c8fba4b.html" title="Last updated on Dec 13, 2020, 8:25 PM UTC (c8fba4b)">Diff</a>

Change MUST to SHOULD for lossless conversion

---

index.html

Add JSON-LD Production and Consumption rules by just referring to the JSON production rules, and layering `@context` above those rules.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/474.html" title="Last updated on Dec 13, 2020, 8:27 PM UTC (ea2e8e9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/474/3d76cea...ea2e8e9.html" title="Last updated on Dec 13, 2020, 8:27 PM UTC (ea2e8e9)">Diff</a>

Add JSON-LD Production and Consumption rules.

---

index.html

This removes the data conversion section in the CBOR section as it duplicates the Representation->Abstract Data Model->Representation rules defined in the Representation section.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/475.html" title="Last updated on Dec 13, 2020, 8:30 PM UTC (2022d43)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/475/f1b5b00...2022d43.html" title="Last updated on Dec 13, 2020, 8:30 PM UTC (2022d43)">Diff</a>

Remove duplicate data conversion section.

---

index.html

This PR replaces #477 (because it had extraneous commits).
***
<a href="https://pr-preview.s3.amazonaws.com/talltree/did-core/pull/484.html" title="Last updated on Dec 19, 2020, 4:44 AM UTC (f67b606)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/484/16ba782...talltree:f67b606.html" title="Last updated on Dec 19, 2020, 4:44 AM UTC (f67b606)">Diff</a>

At Risk statement for ABNF not allowing an empty method-id-string

---

index.html

Addresses https://github.com/w3c/did-core/issues/464
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/485.html" title="Last updated on Dec 17, 2020, 2:24 PM UTC (1bb6dfa)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/485/16ba782...1bb6dfa.html" title="Last updated on Dec 17, 2020, 2:24 PM UTC (1bb6dfa)">Diff</a>

Add advisement on computing the cryptographic hash of a context

---

index.html

Addresses https://github.com/w3c/did-core/issues/417
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/487.html" title="Last updated on Dec 12, 2020, 6:42 PM UTC (365cecc)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/487/16ba782...365cecc.html" title="Last updated on Dec 12, 2020, 6:42 PM UTC (365cecc)">Diff</a>

Define representation-not-supported error

---

index.html

https://github.com/w3c/did-core/issues/432
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/488.html" title="Last updated on Dec 20, 2020, 4:07 PM UTC (0fcd139)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/488/16ba782...0fcd139.html" title="Last updated on Dec 20, 2020, 4:07 PM UTC (0fcd139)">Diff</a>

Remove reference to @base issue discussion.

---

index.html

Addresses:
https://github.com/w3c/did-core/issues/423
https://github.com/w3c/did-core/issues/240
Describes how verification method types are related to key representations.
Removes "key types".
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/490.html" title="Last updated on Dec 20, 2020, 4:20 PM UTC (c3da0b6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/490/16ba782...c3da0b6.html" title="Last updated on Dec 20, 2020, 4:20 PM UTC (c3da0b6)">Diff</a>

Refactor verification methods section

---

index.html

For Issue #491
***
<a href="https://pr-preview.s3.amazonaws.com/shigeya/did-core/pull/492.html" title="Last updated on Dec 20, 2020, 4:25 PM UTC (42183ea)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/492/2eef04c...shigeya:42183ea.html" title="Last updated on Dec 20, 2020, 4:25 PM UTC (42183ea)">Diff</a>

Changing DID method name description to match the ABNF definition to allow digits

---

terms.html

As the subject reads.
Added section reference, also added missing '#' in one of the references.
***
<a href="https://pr-preview.s3.amazonaws.com/shigeya/did-core/pull/503.html" title="Last updated on Dec 20, 2020, 4:31 PM UTC (44c6caf)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/503/2eef04c...shigeya:44c6caf.html" title="Last updated on Dec 20, 2020, 4:31 PM UTC (44c6caf)">Diff</a>

Minor cross reference fixes to the terminology section

---

index.html

fixes Issue #199 
Signed-off-by: Brent Zundel <brent.zundel@gmail.com>
***
<a href="https://pr-preview.s3.amazonaws.com/brentzundel/did-spec/pull/480.html" title="Last updated on Dec 22, 2020, 5:17 PM UTC (e8ac856)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/480/16ba782...brentzundel:e8ac856.html" title="Last updated on Dec 22, 2020, 5:17 PM UTC (e8ac856)">Diff</a>

Add DID parameter for dereferencing an information resource identified by a DID

---

index.html

Related https://github.com/w3c/did-spec-registries/pull/168
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/489.html" title="Last updated on Dec 12, 2020, 7:08 PM UTC (8388af7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/489/16ba782...8388af7.html" title="Last updated on Dec 12, 2020, 7:08 PM UTC (8388af7)">Diff</a>

Add LinkedDomain example

---

index.html

Attempts to solve an editorial issue so we can close #494 
Digging through the commits it looks like this language came about from @jricher with @msporny handling much of the review in this area during PR #197 in [this commit](https://github.com/w3c/did-core/pull/197/commits/a4df7caedd15dc1d61ce1cf77fceff683b762143#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051R1916)
From the looks of it we may be alright going to this language based on [this commit](https://github.com/w3c/did-core/commit/c1c28469d728830f27b46d73551cb8fff1b2ffe0#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051R2342)
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/507.html" title="Last updated on Dec 20, 2020, 4:32 PM UTC (4db1b10)">Preview</a> | <a …

changes usage of localized rules to previously used language

---

index.html

Specify datetime precision for serializations. Fixes #498.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/509.html" title="Last updated on Dec 27, 2020, 6:24 PM UTC (3027601)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/509/5366635...3027601.html" title="Last updated on Dec 27, 2020, 6:24 PM UTC (3027601)">Diff</a>

Specify datetime precision for serializations.

---

index.html

This PR fixes an oversight in the definition of serviceEndpoint to be an array. This should address #506.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/510.html" title="Last updated on Dec 20, 2020, 9:57 PM UTC (668ca83)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/510/6434f17...668ca83.html" title="Last updated on Dec 20, 2020, 9:57 PM UTC (668ca83)">Diff</a>

Allow serviceEndpoint to be an array. Address #506.

---

index.html

This PR ensures that all metadata properties define a data model and serialization format. This addresses issue #499.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/516.html" title="Last updated on Dec 27, 2020, 9:12 PM UTC (13e9d0c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/516/9605a1e...13e9d0c.html" title="Last updated on Dec 27, 2020, 9:12 PM UTC (13e9d0c)">Diff</a>

Ensure all metadata properties define data model and serialization.

---

index.html

Plural terms should be handled by respec configuration or term mappings.  No need to split the "s" out (which can have the effect of things reading `singular-term s`, i.e., term-space-s).
***
<a href="https://pr-preview.s3.amazonaws.com/TallTed/did-core/pull/517.html" title="Last updated on Jan 3, 2021, 7:57 AM UTC (6a9b9ac)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/517/9605a1e...TallTed:6a9b9ac.html" title="Last updated on Jan 3, 2021, 7:57 AM UTC (6a9b9ac)">Diff</a>

(editorial) fix plural terms

---

index.html

This is for https://github.com/w3c/did-core/issues/520 . 
"Example 37: DID Document with many different verification methods".
***
<a href="https://pr-preview.s3.amazonaws.com/bshambaugh/did-core/pull/521.html" title="Last updated on Jan 2, 2021, 3:54 AM UTC (9b83fe1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/521/9605a1e...bshambaugh:9b83fe1.html" title="Last updated on Jan 2, 2021, 3:54 AM UTC (9b83fe1)">Diff</a>

Added Comma after "EC" in P-256 section of Example 37

---

index.html

This is an alternative embodiment of the "Service Privacy" guidance as proposed by Adrian Gropper in [this comment](https://github.com/w3c/did-core/pull/511#issuecomment-749163897). If accepted, it would supersede #511 and address issue #382.
Signed-off-by: Daniel Hardman <daniel.hardman@gmail.com>
***
<a href="https://pr-preview.s3.amazonaws.com/dhh1128/did-core/pull/515.html" title="Last updated on Jan 10, 2021, 7:09 PM UTC (572e072)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/515/6434f17...dhh1128:572e072.html" title="Last updated on Jan 10, 2021, 7:09 PM UTC (572e072)">Diff</a>

Add section on service privacy

---

index.html

This is a companion PR to issue #518, more exactly its [comment](https://github.com/w3c/did-core/issues/518). Submitting this as a PR may speed up processing in case the group agrees with the conclusions in #518...
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/522.html" title="Last updated on Jan 6, 2021, 7:57 AM UTC (fd01d9c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/522/9605a1e...fd01d9c.html" title="Last updated on Jan 6, 2021, 7:57 AM UTC (fd01d9c)">Diff</a>

Removed the usage of INFRA lists, in favor of ordered sets everywhere.

---

index.html

Updates the at risk text for the `application/did+ld+json` media type.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/524.html" title="Last updated on Jan 10, 2021, 7:24 PM UTC (d48f2c8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/524/c2841ed...d48f2c8.html" title="Last updated on Jan 10, 2021, 7:24 PM UTC (d48f2c8)">Diff</a>

Update at risk text for issue #208.

---

index.html

Attempt to address issue #363 by clarifying the use of the word "authorization" in the specification by being really pedantic about its usage.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/525.html" title="Last updated on Jan 3, 2021, 6:45 PM UTC (15ffd2b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/525/c2841ed...15ffd2b.html" title="Last updated on Jan 3, 2021, 6:45 PM UTC (15ffd2b)">Diff</a>

Address issue #363 by clarifying use of word "authorization".

---

index.html

This PR contains a complete top-to-bottom review of the testability of the normative statements in the DID Core specification and should address issue #384. The goal with this PR is to reduce the workload for the entire WG wrt. the test suite and the tests we're going to have to write in the coming month or two. With that goal in mind - this PR removes or refactors normative statements that are tested elsewhere in the specification, aren't our job to test, or are too vague to be tested (by a human or a machine).
I expect there are a few that reviewers might find concerning, so while you're considering the change, ask yourself the following questions to suggest alternatives:
* Is it the job of the DID Core specification (based on our Charter) to test this particular thing?
* Can this …

Complete top-to-bottom review of testability of normative statements.

---

index.html

resolving merge conflicts in #528 would have been terrible; git's rebase went completely crazy. However, my changes in #528 were fully concentrated to the initial part of §5, so I decided to make a fresh branch and manually transfer my changes instead.
@rhiaro, would you mind checking that the changes here are indeed the same as the changes proposed in #528 (except that they are on the fresh branch)? If so, @msporny, I believe the comments in #528 stand for this one, and this PR could be merged (and #528 simply closed).
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/536.html" title="Last updated on Jan 11, 2021, 1:35 PM UTC (41af738)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/536/c8bc6b1...41af738.html" title="Last updated on Jan 11, 2021, …

Added tables to replace the introductory part on core properties - bis for github

---

index.html

This is an editorial PR that simply changes the order of the [DID parameter table](https://w3c.github.io/did-core/#did-parameters) to list `service` before `relative-ref`.
I agree with the re-ordering done by @rhiaro in https://github.com/w3c/did-core/pull/427/commits/74586e8f3f1c7245e9d725c25850d749aa028cb6, which nicely lists required parameters before optional ones, but I think the table becomes more readable if `service` comes before `relative-ref`. After all, the latter mentions the former, and all the examples I've seen also use them in this order.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/531.html" title="Last updated on Jan 5, 2021, 9:50 PM UTC (fbe4639)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/531/10744a0...fbe4639.html" …

Swap service and relative-ref parameters in table.

---

index.html

Changes equivalent id and canonical id to use hyphens instead of camelCase because the other DID doc metadata properties use hyphens. If I missed an explicit resolution to do these inconsistently, just close the PR..
I don't think this is technically an editorial change, if there are already implementations of these properties with camelCase.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/533.html" title="Last updated on Jan 12, 2021, 7:06 PM UTC (3d9d375)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/533/c8bc6b1...3d9d375.html" title="Last updated on Jan 12, 2021, 7:06 PM UTC (3d9d375)">Diff</a>

Make DID doc metadata propertly names consistent

---

common.js
index.html

I think there was a general feeling that the very specific parts about hashing the JSON-LD context don't belong in the Core spec (https://github.com/w3c/did-core/pull/485#issuecomment-744068170). https://github.com/w3c/did-spec-registries/pull/146 on the registries adds the specifics there instead. I also added a bit about this more generally in security considerations.
This _removes_ a normative statement in favour of deferring to the registries and additional informative security guidence.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/534.html" title="Last updated on Jan 17, 2021, 6:53 PM UTC (f6555eb)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/534/10744a0...f6555eb.html" title="Last updated on Jan 17, 2021, 6:53 PM UTC …

Improve content integrity protection parts (mostly about json-ld contexts)

---

terms.html

Addresses #545.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/546.html" title="Last updated on Jan 13, 2021, 1:32 AM UTC (1279415)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/546/c8bc6b1...1279415.html" title="Last updated on Jan 13, 2021, 1:32 AM UTC (1279415)">Diff</a>

Remove mention of DID document as input in DID URL dereferencing term definition

---

terms.html

Very small change to improve a reference, purely editorial.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/547.html" title="Last updated on Jan 13, 2021, 1:38 AM UTC (77a476c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/547/c8bc6b1...77a476c.html" title="Last updated on Jan 13, 2021, 1:38 AM UTC (77a476c)">Diff</a>

Link "DID resolution" term directly to corresponding section.

---

index.html

This is an attempt to address #399, in order to clarify that DID URL dereferencing returns the final resource (including when the DID URL contains a fragment). How this is implemented is out of scope for DID Core.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/544.html" title="Last updated on Jan 13, 2021, 4:04 PM UTC (68795c4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/544/c8bc6b1...68795c4.html" title="Last updated on Jan 13, 2021, 4:04 PM UTC (68795c4)">Diff</a>

Clarify that DID URL dereferencing returns the final resource.

---

index.html

This is related to issue #549 and presumes that the group wants to mark the section at risk before going into CR. Looking to see if folks in the group would object to this language. Note that at risk doesn't mean we're going to remove it -- it means, we have implementation concerns.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/550.html" title="Last updated on Jan 24, 2021, 4:56 PM UTC (6981692)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/550/af9c06b...6981692.html" title="Last updated on Jan 24, 2021, 4:56 PM UTC (6981692)">Diff</a>

Add at risk marker to Resolution section.

---

index.html

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/561.html" title="Last updated on Jan 19, 2021, 1:51 PM UTC (13bf3dd)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/561/4ecfda7...13bf3dd.html" title="Last updated on Jan 19, 2021, 1:51 PM UTC (13bf3dd)">Diff</a>

markup: remove spacing around headings, fixes #537

---

index.html

In https://github.com/w3c/did-core/pull/533, metadata property names were changed from using hyphens to camelCase (e.g. `content-type` -> `contentType`). That same PR also changed both the `version-id` metadata property and the `version-id` DID parameter to `versionId`.
This PR here changes the remaining two concerned DID parameters `relative-ref` and `version-id` to be consistent with the others.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/553.html" title="Last updated on Jan 18, 2021, 10:21 AM UTC (935f753)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/553/af9c06b...935f753.html" title="Last updated on Jan 18, 2021, 10:21 AM UTC (935f753)">Diff</a>

Change DID parameter names to camelCase.

---

index.html

Adds a comment like `// external (property name)` to differentiate terms not defined in Core, as suggested by @iherman. Also explains this notation the Conformance section.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/562.html" title="Last updated on Jan 19, 2021, 3:12 PM UTC (fd269eb)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/562/4ecfda7...fd269eb.html" title="Last updated on Jan 19, 2021, 3:12 PM UTC (fd269eb)">Diff</a>

examples: differentiate external properties, fixes #447

---

index.html

I feel like we're saying "service endpoint" in a lot of places where we should be saying "service". A service may or may not have a service endpoint.
**EDIT:** The second sentence above is wrong; see discussion below.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/564.html" title="Last updated on Jan 25, 2021, 6:35 AM UTC (136216c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/564/2e78762...136216c.html" title="Last updated on Jan 25, 2021, 6:35 AM UTC (136216c)">Diff</a>

Replace "service endpoint" with "service" where appropriate.

---

index.html

This is the alternative to #554 : removing the example of a service with a verification method.
This is also relevant to #404.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/565.html" title="Last updated on Jan 28, 2021, 11:00 AM UTC (a650f65)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/565/090f81f...a650f65.html" title="Last updated on Jan 28, 2021, 11:00 AM UTC (a650f65)">Diff</a>

Removing example with verification method in a service

---

index.html

As per @peacekeeper request, I tried to come up with a PR that covers LoAs; fixes #151
***
<a href="https://pr-preview.s3.amazonaws.com/awoie/did-core/pull/568.html" title="Last updated on Jan 26, 2021, 5:54 PM UTC (3c373df)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/568/2e78762...awoie:3c373df.html" title="Last updated on Jan 26, 2021, 5:54 PM UTC (3c373df)">Diff</a>

Added Level of Assurance (LoA) section; fixes #151; fixes #391

---

index.html

This addresses https://github.com/w3c/did-core/issues/463 to re-use the INFRA terms "entries", "keys" and "values", and clarifies that the data model supports properties such as `id`, `verificationMethod`, `service`, etc. as well as representation-specific entries such as `@context`. This PR mostly avoids the term "syntax". This PR also honors the agreement of the Virtual F2F that representation-specific entries such as `@context` are included in the abstract data model and preserved.
The central paragraph in this PR for the [Data Model](https://w3c.github.io/did-core/#data-model) section is this:
_A DID document consists of a map of entries, where each entry consists of an entry key/entry value pair. The data model contains at least two different classes of entries. The first class of …

Clarify that the data model supports properties and representation-specific entries.

---

index.html

Previous PR was corrupted with merge conflicts, this was an easier way for me to get a clean change-set...
All feedback as existing on the previous PR has been implemented (but not accepted)
https://github.com/w3c/did-core/pull/548
Specifically @dhh1128 please request any changes on this PR that I failed to address.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/569.html" title="Last updated on Jan 31, 2021, 2:41 PM UTC (cff7eed)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/569/f2bfa86...cff7eed.html" title="Last updated on Jan 31, 2021, 2:41 PM UTC (cff7eed)">Diff</a>

Add rotation and recovery sections from previous PR

---

index.html

Per resolution https://www.w3.org/2019/did-wg/Meetings/Minutes/2021-01-14-did-topic#resolution1
PR opened in DID Spec Registries to add it, but that is incomplete as it the definition needs to go into another document. Who is taking ownership of this parameter?
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/572.html" title="Last updated on Jan 23, 2021, 9:15 PM UTC (1a7cc16)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/572/2e78762...1a7cc16.html" title="Last updated on Jan 23, 2021, 9:15 PM UTC (1a7cc16)">Diff</a>

parameters: Remove resource parameter

---

index.html

Following @iherman's addition of a summary table to Core Properties, I did a full review of the section to remove redundant language, make sure there is no duplicate normative language and no inconsistencies, and adjust the structure a little to improve readability.
I marked the summary table as explicitly non-normative. All normative language remains in the subsequent sections which contain the full property definitions and longer descriptions of what the properties are for.
https://github.com/w3c/did-core/commit/ffb6c2b056189e8af310c8bc4d2885e4e994a16a replaces the algorithm for getting verification methods by reference with a couple of sentences instead. I can roll this back if necessary, but I find it less jarring to read in the context of the rest of the section.
I touched on #452 in …

Clean up Core Properties

---

index.html

The note on persistence of DIDs was revised per the text discussed on [slide 34 of the presentation deck](https://docs.google.com/presentation/d/1RoE8E4y8S1j65EJaXZ8oihkduNbjTXXvdwtkzw961Xw/edit?pli=1#slide=id.ga6aa7427ae_1_61) for the DID WG TPAC virtual F2F session.
***
<a href="https://pr-preview.s3.amazonaws.com/talltree/did-core/pull/457.html" title="Last updated on Jan 31, 2021, 9:41 PM UTC (d0c16e2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/457/c92b13c...talltree:d0c16e2.html" title="Last updated on Jan 31, 2021, 9:41 PM UTC (d0c16e2)">Diff</a>

DIDs as Enhanced URNs

---

index.html

***
<a href="https://pr-preview.s3.amazonaws.com/csuwildcat/did-core/pull/581.html" title="Last updated on Feb 4, 2021, 2:18 PM UTC (355b2d7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/581/c8bc6b1...csuwildcat:355b2d7.html" title="Last updated on Feb 4, 2021, 2:18 PM UTC (355b2d7)">Diff</a>

Deactivated flag moved to DID Document Metadata

---

index.html

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/589.html" title="Last updated on Feb 1, 2021, 4:35 PM UTC (969cc9d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/589/39877b1...969cc9d.html" title="Last updated on Feb 1, 2021, 4:35 PM UTC (969cc9d)">Diff</a>

at risk: mark alsoKnownAs at risk, for #584

---

index.html

This PR implements the WG decision to decouple DagCBOR from DID Core and move it into it's own specification. The resolution can be found here: https://www.w3.org/2021/02/02-did-minutes.html#r01
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/593.html" title="Last updated on Feb 2, 2021, 10:55 PM UTC (b84f561)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/593/bad3368...b84f561.html" title="Last updated on Feb 2, 2021, 10:55 PM UTC (b84f561)">Diff</a>

Remove DagCBOR from the specification.

---

index.html

The "at risk" markers in the spec had strikes through them as they were linked to closed issues. This might make them easy to miss, as it is common not to bother reading things with strikethroughs. I un-autolinked the issues and added the titles and issue link back in by hand to fix this.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/604.html" title="Last updated on Feb 7, 2021, 8:56 PM UTC (d5b6b21)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/604/59687a4...d5b6b21.html" title="Last updated on Feb 7, 2021, 8:56 PM UTC (d5b6b21)">Diff</a>

editorial: remove strikethrough from feature at risk issues

---

index.html

***
<a href="https://pr-preview.s3.amazonaws.com/TallTed/did-core/pull/605.html" title="Last updated on Feb 8, 2021, 6:01 PM UTC (49b88ea)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/605/e5cf7f3...TallTed:49b88ea.html" title="Last updated on Feb 8, 2021, 6:01 PM UTC (49b88ea)">Diff</a>

fixing `i.e.,` and `e.g.,` punctuation

---

index.html

This PR is intended to address issue #549 by adding to the abstract functions discussed in the DID Resolution and DID URL Dereferencing sections and ensuring that all statements are testable using a "proof by construction". That is, all statements that return abstract data models are testable due to additional normative statements that effectively state: "anything that returns an abstract data model MUST be serializable in one of the representations". Previously, that statement didn't apply to `didDocument`, the metadata structure, some of the dereferencing values, etc. This PR fixes that.
The PR also adds at-risk markers to some of the newer features requested by individuals (but not necessarily broadly requested by the WG -- such as nextUpdate, nextVersionId, equivalentId, and …

Clean up DID Resolution section; enable testability via proof by construction

---

index.html

It is currently not clear who is going to volunteer to write tests for the CBOR section or if all of the section is implementable. For example, there is still disagreement over whether the "canonicalization rules" constitute a "canonicalization algorithm" and whether or not the intent is for those rules to produce a deterministic canonical form that can be used to generate digital signatures or not. For these reasons, we should mark the section as at risk.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/594.html" title="Last updated on Feb 9, 2021, 9:30 PM UTC (2b73643)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/594/6f647ff...2b73643.html" title="Last updated on Feb 9, 2021, 9:30 PM UTC (2b73643)">Diff</a>

Mark CBOR as a feature at risk.

---

index.html

@jonnycrunch I've been coordinating with @msporny on a few improvements to the CBOR section:
* Reference the Canonical CBOR rules from RFC7049 instead of duplicating that text.
* Some bug fixes (text strings are major type 3, not 5).
* Removed some unnecessary language that duplicates what's already specified elsewhere (e.g. that all entries of the DID document must be included, or that unknown properties must be preserved).
Does this work for you? I think this would also replace https://github.com/w3c/did-core/pull/586.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/606.html" title="Last updated on Feb 11, 2021, 4:36 PM UTC (6d3a5bc)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/606/e5cf7f3...6d3a5bc.html" title="Last updated on Feb 11, …

Reference Canonical CBOR rules, and some other fixes.

---

index.html

This PR adds the CR header config values to the DID Core spec.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/607.html" title="Last updated on Feb 9, 2021, 10:18 PM UTC (4524c4b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/607/6645c05...4524c4b.html" title="Last updated on Feb 9, 2021, 10:18 PM UTC (4524c4b)">Diff</a>

Add Candidate Recommendation variables to spec.

---

index.html

Okay I know how controversial this will be, considering the discussions around my diagrams in https://github.com/w3c/did-core/pull/596 and https://github.com/w3c/did-core/pull/597), but I have to try.
This changes the language around `@context` in the JSON-LD production/consumption sections to treat it primarily as a member in a JSON object (concrete DID document representation), rather than an entry in the INFRA map (abstract DID document data model).
Explanation:
The JSON-LD production section as it's currently written seems to contradict itself. First it says
_"The DID document **MUST include the @context entry.**"_
but then it says
_"This entry [..] **could be present** [..]. **If the entry is present**" [..]._
I am pretty sure the intention here is to say that `@context` MUST be …

Describe `@context` as JSON member in JSON-LD production/consumption.

---

index.html

WARNING: This PR removes two normative statements that duplicate requirements asserted in the ABNF. So, while the changes are normative changes, they are non-substantive.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/620.html" title="Last updated on Feb 12, 2021, 5:31 PM UTC (3becb6b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/620/5d0cdbc...3becb6b.html" title="Last updated on Feb 12, 2021, 5:31 PM UTC (3becb6b)">Diff</a>

Fix editorial and normative issues in DID Syntax section.

---

index.html

This PR creates a new normative requirement that I expect the WG intended to have in the specification, but failed to assert regarding the DID URL ABNF Syntax. At no point did we say that conforming producers and consumers MUST follow the ABNF rules. Woops.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/621.html" title="Last updated on Feb 12, 2021, 5:36 PM UTC (b0cbde0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/621/5d0cdbc...b0cbde0.html" title="Last updated on Feb 12, 2021, 5:36 PM UTC (b0cbde0)">Diff</a>

Fix editorial and normative issues in DID URL Syntax section.

---

index.html

This PR removes some duplicated normative requirements, moves DID Method normative requirements to the section on DID Methods, harmonizes the links to RFC3986, and fixes a few examples.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/622.html" title="Last updated on Feb 12, 2021, 5:52 PM UTC (e147489)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/622/ceb52fe...e147489.html" title="Last updated on Feb 12, 2021, 5:52 PM UTC (e147489)">Diff</a>

Fix editorial/normative issues in Path, Query, and Fragment sections.

---

index.html

We should be consistent with these terms, they have been changed back and forth a few times e.g. in PRs https://github.com/w3c/did-core/pull/232 or https://github.com/w3c/did-core/pull/535.
In my opinion "personal data" is the more modern and universal term.
Wikipedia https://en.wikipedia.org/wiki/Personally_identifiable_information redirects to https://en.wikipedia.org/wiki/Personal_data.
Fixes https://github.com/w3c/did-core/issues/590.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/623.html" title="Last updated on Feb 11, 2021, 5:58 PM UTC (e997504)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/623/1dda7f5...e997504.html" title="Last updated on Feb 11, 2021, 5:58 PM UTC (e997504)">Diff</a>

Change "personally-identifiable information" to "personal data".

---

index.html

Addresses https://github.com/w3c/did-core/issues/618
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/624.html" title="Last updated on Feb 11, 2021, 9:46 PM UTC (daa2fee)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/624/1dda7f5...daa2fee.html" title="Last updated on Feb 11, 2021, 9:46 PM UTC (daa2fee)">Diff</a>

Change "DID dereferencing" to "DID URL dereferencing".

---

index.html

Mostly editorial clean ups. Two normative REQUIRED statements around `service` and `relativeRef` were downgraded to OPTIONAL because keeping them at REQUIRED would make the `did:key` DID method invalid -- `did:key` has no support for `service` endpoints or `relativeRef`.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/627.html" title="Last updated on Feb 16, 2021, 1:50 PM UTC (56c0bff)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/627/1dda7f5...56c0bff.html" title="Last updated on Feb 16, 2021, 1:50 PM UTC (56c0bff)">Diff</a>

Fix editorial/normative issues in DID Parameters.

---

index.html

This adds an example of a DID document in the JSON representation. @msporny @OR13 do you agree with this?
This example shows the same DID document in JSON that we already have as an example in the CBOR section.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/628.html" title="Last updated on Feb 12, 2021, 4:31 AM UTC (b6dede2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/628/1dda7f5...b6dede2.html" title="Last updated on Feb 12, 2021, 4:31 AM UTC (b6dede2)">Diff</a>

Add DID document example in JSON representation.

---

index.html

This PR reworks the `id`, `controller`, and `alsoKnownAs` properties into a section called `Identification`. Two of the normative statements have been combined into one. One of the normative statements was moved to the Resolution section (because it had to do with the resolution process). There should be no substantive changes in this PR.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/632.html" title="Last updated on Feb 16, 2021, 3:02 PM UTC (f51eac7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/632/b554e1c...f51eac7.html" title="Last updated on Feb 16, 2021, 3:02 PM UTC (f51eac7)">Diff</a>

Fix editorial issues in Identification section.

---

common.js
index.html

This PR attempts to condense much of the language in the Verification Methods section, retitle some sections, and condense a few normative statements that were duplicates. It also introduces the concept that we're looking for feedback wrt. publicKeyBase58 and publicKeyMultibase as verification material properties. The editorial rework is significant, but all changes should be non-substantive.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/635.html" title="Last updated on Feb 16, 2021, 3:10 PM UTC (b19057c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/635/9b373a1...b19057c.html" title="Last updated on Feb 16, 2021, 3:10 PM UTC (b19057c)">Diff</a>

Fix non-substantive issues with Verification Methods section.

---

index.html

This PR is intended to be non-substantive. I merged a few normative statements and removed language which seemed to duplicate language in this section or elsewhere in the specification. The biggest change was removing a whole bunch of example service endpoints for which there are no existing specifications. There were complaints about us using examples that were not grounded in existing specification text. If I removed one that does have a specification, please let me know. Everything else should have been an editorial change.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/642.html" title="Last updated on Feb 16, 2021, 3:36 PM UTC (d234315)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/642/d355bda...d234315.html" title="Last updated on Feb …

Fix non-substantive issues with Service section.

---

index.html

The definition is missing in the conformance section.
***
<a href="https://pr-preview.s3.amazonaws.com/shigeya/did-core/pull/643.html" title="Last updated on Feb 15, 2021, 10:17 AM UTC (043c7bf)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/643/d355bda...shigeya:043c7bf.html" title="Last updated on Feb 15, 2021, 10:17 AM UTC (043c7bf)">Diff</a>

Adding definition of 'conforming DID URL dereferencer'

---

index.html

Remove the Current Issues appendix. We shouldn't have one when going into Candidate Recommendation because all issues have been either addressed or defered.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/649.html" title="Last updated on Feb 15, 2021, 3:55 PM UTC (34325de)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/649/d355bda...34325de.html" title="Last updated on Feb 15, 2021, 3:55 PM UTC (34325de)">Diff</a>

Remove Current Issues appendix.

---

index.html

This should have been removed by PR #593 https://github.com/w3c/did-core/pull/593/files#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051L6254 ... but the section has somehow reappeared in the spec. Removing again. Harder, this time.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/650.html" title="Last updated on Feb 15, 2021, 5:20 PM UTC (631174a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/650/d355bda...631174a.html" title="Last updated on Feb 15, 2021, 5:20 PM UTC (631174a)">Diff</a>

Remove the IANA section for application/did+dag+cbor.

---

index.html

This is the PR version of issue #647 on the introductory paragraph of [§3.2](https://w3c.github.io/did-core/#did-url-syntax).
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/655.html" title="Last updated on Feb 16, 2021, 4:15 PM UTC (b769f1d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/655/d355bda...b769f1d.html" title="Last updated on Feb 16, 2021, 4:15 PM UTC (b769f1d)">Diff</a>

Editorial change on the introductory para DID URL

---

index.html

This PR cleans up the introductory portion of the Representations section by 1) providing a non-normative background to what representation/production/consumption is, 2) groups the normative statements into 3 groups -- all representations, all conforming producers, and all conforming consumers, 3) downgrades a MAY statement that wasn't easily testable but keeps the language around to make the intent clear. I tried to keep the essence of the section intact, but did end up modifying a few normative statements... so this PR makes substantive changes while trying to preserve what the section was doing.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/644.html" title="Last updated on Feb 17, 2021, 8:27 PM UTC (81e4417)">Preview</a> | <a …

Fix substantive issues related to Representations intro section.

---

index.html

This PR attempts to clean up the JSON Production and Consumption section in a way that enables the data model to be serialized for data structures other than a DID Document (to align it with the Resolution serialization requirements), while keeping the DID Document serialization rules more or less the same. There was wierdness related to tying the resolution section in normatively to the production/consumption rules, which really should be done higher up in the stack. I'm marking it as substantive because, while I'm fairly certain implementations wouldn't be affected by the changes, normative language was changed/merged/removed.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/653.html" title="Last updated on Feb 17, 2021, 8:33 PM UTC (fd066c8)">Preview</a> | <a …

Fix editorial and substantive issues in JSON Production and Consumption section.

---

index.html

This PR is a fairly significant restructuring of the JSON-LD section. All the previous normative statements are more or less still active, save for the ones that are handled by other parts of the specification. I don't think implementations would need to change based on the modifications in this section, but I'm still marking it as a substantive change so people put a bit more diligence into reviewing it to make sure it does everything important that was being done before while attempting to simplify the language a bit (and cover some edge cases/advisements).
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/654.html" title="Last updated on Feb 17, 2021, 8:42 PM UTC (4654bf5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/654/d355bda...4654bf5.htm …

Fix editorial and substantive issues in JSON-LD section.

---

index.html

https://github.com/w3c/did-core/pull/627 removed an example of a DID URL with a `service` parameter. I think it would be helpful to have such an example, so this PR adds one again.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/657.html" title="Last updated on Feb 18, 2021, 2:09 PM UTC (be2cbcf)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/657/7839264...be2cbcf.html" title="Last updated on Feb 18, 2021, 2:09 PM UTC (be2cbcf)">Diff</a>

Restore example of 'service' and 'relativeRef' parameters.

---

index.html

backticks -> `<code />`
and associated line lengths
***
<a href="https://pr-preview.s3.amazonaws.com/TallTed/did-core/pull/660.html" title="Last updated on Feb 16, 2021, 5:00 PM UTC (7dfff7e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/660/9f78b2c...TallTed:7dfff7e.html" title="Last updated on Feb 16, 2021, 5:00 PM UTC (7dfff7e)">Diff</a>

(editorial) replace some markdown with html tags

---

index.html

This PR reworks the CBOR section in the same way the JSON and JSON-LD sections were reworked. The changes are largely editorial or non-substantive, but there is one change that is substantive. 
There were rules regarding preserving "unknown data types"... except that there is no such thing in the ADM... we either know about the data type, or we can't represent it in the ADM. It is impossible for an "unknown data type" to exist in the ADM... all data types are known, or they're not representable. Similarly, it is impossible for a CBOR consumer to consume data with an unknown data type and preserve it in the ADM... because there is nowhere to put it (because the data type is unknown). You can't convert it to a string (which is what was specified) because the production rules would spit it …

Fix editorial and substantive issues in CBOR section.

---

terms.html

Most changes are purely editorial. Except two things:
(1) I have changed a cross reference in the terminology description for DID Methods. Please check whether that is all right
(2) I have found an oddity in the description of **representation**. There is a cross reference which says "DID Core: Representations."; its HTML source code is:
```
See <a href="https://w3.org/TR/did-core#representations">DID Core: Representations</a>
```
although in all other places the internal, respec-like reference is used, e.g., this should look like
```
See <a href="#representations"></a>
```
However, I did **_not_** changed this (yet) because, afaik, this separate `term.html` file is (was?) also used by the UCR document and I did not want to create a problem. @jandrieu @philarcher would there be a problem …

Editorial review of the terminology section

---

index.html

All entries in the parameter table in §3.2.1 have a repeating "Support for this parameter is OPTIONAL." remark. For reasons of readability the remark has been put in the text above the table and these remarks have been removed from the items themselves.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/675.html" title="Last updated on Feb 19, 2021, 7:52 AM UTC (8d0fbc1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/675/bb89040...8d0fbc1.html" title="Last updated on Feb 19, 2021, 7:52 AM UTC (8d0fbc1)">Diff</a>

Factoring out the 'OPTIONAL' for the parameter table.

---

terms.html

Moving the discussion here from #672: changing the description for DID-s in the terminology section.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/676.html" title="Last updated on Feb 18, 2021, 4:59 PM UTC (5840240)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/676/bb89040...5840240.html" title="Last updated on Feb 18, 2021, 4:59 PM UTC (5840240)">Diff</a>

Changed the DID terminology entry (see issue #672)

---

index.html

This remark is also present in the INFRA spec, and it is better to have it because our spec often just refers to a "map" instead of "ordered map".
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/677.html" title="Last updated on Feb 18, 2021, 5:15 PM UTC (eb4b98f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/677/bb89040...eb4b98f.html" title="Last updated on Feb 18, 2021, 5:15 PM UTC (eb4b98f)">Diff</a>

Added a remark whereby an ordered map is sometimes just referred to as "map".

---

index.html

See #674 for the underlying discussion.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/682.html" title="Last updated on Feb 21, 2021, 9:07 PM UTC (3b50f66)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/682/69f7eff...3b50f66.html" title="Last updated on Feb 21, 2021, 9:07 PM UTC (3b50f66)">Diff</a>

Changed the note on semicolon usage

---

index.html

The introductory paragraph in [§5.1](https://w3c.github.io/did-core/#identifiers) says:
> It is necessary to learn the identifiers used within a DID document to refer to the DID subject and the DID controller, as well as any alternate identifiers that might also be used to reference the DID subject. The following section elaborates on the mechanisms the DID document data model provides for so doing.
I was not fully sure  what this paragraph really tries to say and, in any case, "necessary to learn" is not an acceptable style for a specification. Also, the generic statement on identifiers is not accurate: identifiers in a DID document are also used to identify verification methods or services.
The PR proposes an alternate formulation based on my understanding (which may be entirely …

Re-writing the intro paragraph of §5.1

---

index.html

I have completed the second pass to make sure that all machine-testable normative MUST/REQUIRED statements are, in fact, machine testable. There was only one issue that I found, a missing link around a `string` type. I also cleaned up the "ordered map" language -> just "map"... because we don't expect people to assume the maps are ordered so we should stop saying "ordered map" everywhere and just say "map".
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/686.html" title="Last updated on Feb 21, 2021, 9:14 PM UTC (f7f247f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/686/a93c6c0...f7f247f.html" title="Last updated on Feb 21, 2021, 9:14 PM UTC (f7f247f)">Diff</a>

Fix "ordered map" language and ensure testability of all MUST statements.

---

index.html

Implements the following WG decision:
> RESOLUTION: The ADM is only used to represent a DID document or parts of a DID document (e.g. a verification method). For DID Resolution data structures, INFRA will be referenced normatively, as well as the JSON serialization rules for INFRA, to note that the data structure must be able to be serialized using INFRA->JSON rules.
https://www.w3.org/2021/02/16-did-topic-minutes.html#r01
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/678.html" title="Last updated on Feb 22, 2021, 2:32 PM UTC (919d1ba)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/678/793057f...919d1ba.html" title="Last updated on Feb 22, 2021, 2:32 PM UTC (919d1ba)">Diff</a>

Implement Data Model / Resolution serialization mechanisms.

---

index.html

This PR attempts to address @peacekeeper's long standing concern wrt. production and consumption and representation-specific entries by using the proposal for Option 3.3 in issue https://github.com/w3c/did-core/issues/664#issuecomment-780647353. This is also an attempt to get PRs #596 and #597 unstuck. 
Specifically, it defines the input and return parameters for conforming producers and consumers and splits the representation-specific entries into their own map that can be serialized and returned along with the DID Document data model. It adds a requirement that all representations detect known representation-specific entries, which is required to cleanly create the two classes of information. The change is substantive.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/67 …

Add representation-specific entry map in Production and Consumption.

---

index.html

This changes `deactivated` to be a DID document metadata property rather than error. This change was previously done in https://github.com/w3c/did-core/pull/581, but then apparently got lost somehow.
Addresses https://github.com/w3c/did-core/issues/687.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/691.html" title="Last updated on Feb 22, 2021, 10:54 AM UTC (af6736a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/691/14c5fa3...af6736a.html" title="Last updated on Feb 22, 2021, 10:54 AM UTC (af6736a)">Diff</a>

Move 'deactivated' to DID document metadata (again).

---

index.html

I believe this is the correct fix for https://github.com/w3c/did-core/issues/689, but need review by @jricher to make sure.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/696.html" title="Last updated on Feb 23, 2021, 4:49 PM UTC (d5a5e65)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/696/3313fc6...d5a5e65.html" title="Last updated on Feb 23, 2021, 4:49 PM UTC (d5a5e65)">Diff</a>

Fix mistake regarding empty didResolutionMetadata.

---

diagrams/did_url_dereference_overview.svg
index.html

Added in Sec 8.2. DID URL Dereferencing.
Place prior to the function signature. Small amount of text added.
Attached is the added diagram for review convinience. 
Note: I've adjusted placement of properties inside DID document due to readability. May need to update other figure to match to this version.
***
<a href="https://pr-preview.s3.amazonaws.com/shigeya/did-core/pull/648.html" title="Last updated on Feb 15, 2021, 11:51 AM UTC (5d3c3ae)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/648/d355bda...shigeya:5d3c3ae.html" title="Last updated on Feb 15, 2021, 11:51 AM UTC (5d3c3ae)">Diff</a>

Add a diagram depicts DID URL dereference

---

index.html

After some discussion around key revocation with @OR13 he suggested that I add some additional context on how to securely verify proofs / signatures that where made in the past with a revoked key.
***
<a href="https://pr-preview.s3.amazonaws.com/oed/did-core/pull/668.html" title="Last updated on Feb 26, 2021, 1:25 PM UTC (b8574e5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/668/f768dd1...oed:b8574e5.html" title="Last updated on Feb 26, 2021, 1:25 PM UTC (b8574e5)">Diff</a>

Add additional note to Verification Method Revocation section

---

index.html

As noted in #684, our IANA Mediat Type filename extensions collide. This has been fixed using the only option available to us (that follows the patterns in other Media Type extensions). 
I considered the following patterns:
1. Keep all of them as `.did` -- this fails because associated file media type information isn't always preserved on copy and a system falling back to the file extension wouldn't be able to determine the file format based on OS MAGIC numbers (byte headers -- JSON and JSON-LD headers are the same).
2. Use `.did.json`, `.did.jsonld`, and `.did.cbor` -- looks nice, but there isn't a single example of this pattern in `/etc/mime.types` and it broke 3 of the 5 media type libraries I tested.
3. Use `.djs`, `.dld`, `.dcb` -- compatible with every known OS and filesystem going …

Fix collisions in IANA Media Type file extensions.

---

index.html

This PR is being raised to address issue #699, which was a bug in the spec.
Marking this as substantive as it affects implementations.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/703.html" title="Last updated on Feb 26, 2021, 4:25 PM UTC (7220ae6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/703/ed12dd5...7220ae6.html" title="Last updated on Feb 26, 2021, 4:25 PM UTC (7220ae6)">Diff</a>

Add support for percent-encoded characters for did:web.

---

index.html

This PR moves a few conformance statements around to migrate the normative requirements from the conformance section to the section on production/consumption (in order to group the production/consumption statements w/ the other statements).
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/705.html" title="Last updated on Mar 1, 2021, 3:02 AM UTC (ddfea73)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/705/c436145...ddfea73.html" title="Last updated on Mar 1, 2021, 3:02 AM UTC (ddfea73)">Diff</a>

Align conformance statements.

---

index.html

Affects normative language, but is definitely a copy-paste induced typo.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/706.html" title="Last updated on Mar 1, 2021, 3:11 PM UTC (f4f39f8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/706/4f4a7b1...f4f39f8.html" title="Last updated on Mar 1, 2021, 3:11 PM UTC (f4f39f8)">Diff</a>

editorial: fix typo in services

---

common.js

There is a mysterious bug in respec and/or specref, which means that the JSON-LD11 and VC Data model references are wrong: they refer to a WD and a PR, respectively. Mainly the first one is an issue for a CR publication.
Have tried to track down the bug to yield a proper error report on specref or respec, but it does not seem to be easy (on a simple example it works correctly). As a temporary measure, to make the publication of the CR possible, I have modified, in this branch, the local biblio structure on common.js by adding both of those explicitly with the right parameters. We should use this for the CR publication.
Sigh...

Handling a respec/specref error

---

.travis.yml
ECHIDNA

With the CR publication, the usage of ECHIDNA changes (see [separate ECHIDNA page](https://github.com/w3c/echidna/wiki/CR-publication-workflow)):
1. Any editorial CR update can be made on a CR via ECHIDNA
2. A substantial CR update must require a Director's approval, and has to go through the staff contact and the W3C Webmaster
This PR makes the necessary changes on the ECHIDNA setup.

Post-CR Changes on ECHIDNA (DO NOT MERGE THIS BEFORE CR PUBLICATION)

---

common.js

The new one is https://datatracker.ietf.org/doc/html/draft-multiformats-multibase-03, and the date is February 2021

Updated the multibase doc. reference

---

index.html

This PR removes the "AT RISK" notes for `nextUpdate` and `nextVersionId`.
According to https://github.com/w3c/did-core/issues/667#issuecomment-781359169 this can be done now that there are tests and two independent implementations of these features (`did:3` and `did:ethr`).
***
<a href="https://pr-preview.s3.amazonaws.com/oed/did-core/pull/722.html" title="Last updated on Apr 21, 2021, 7:58 AM UTC (4fc23ae)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/722/10487e0...oed:4fc23ae.html" title="Last updated on Apr 21, 2021, 7:58 AM UTC (4fc23ae)">Diff</a>

chore: Remove at risk note for nextUpdate and nextVersionId

---

index.html

For #728 
Removed FAQ style headings and responses, trimmed down some text, made some language consistent.
Note - one subsection said DID docs can be used to serve representations of resources, like schemas. I thought the group had resolved that DID docs should have minimal stuff for the specific needs of DIDs, and that any more than this was bad practice (per the `resource=true` discussion) so I've updated it to say to use a DID parameter to do this but didn't mention the `resource` parameter as [it still doesn't have a spec linked in the Registries](https://github.com/w3c/did-spec-registries/issues/244). This is a separate commit though so can revert if I got the wrong end of the stick.
Also added a paragraph aiming to address #718 about whether the DID subject can change.
***
<a …

FAQ appendix cleanup

---

index.html

This PR addresses issue #707 by replacing the use of publicKeyBase58 with publicKeyMultibase.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/731.html" title="Last updated on May 15, 2021, 2:43 PM UTC (0be2206)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/731/79893da...0be2206.html" title="Last updated on May 15, 2021, 2:43 PM UTC (0be2206)">Diff</a>

Replace use of publicKeyBase58 with publicKeyMultibase.

---

index.html

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/744.html" title="Last updated on May 29, 2021, 6:49 PM UTC (cebb246)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/744/435a304...cebb246.html" title="Last updated on May 29, 2021, 6:49 PM UTC (cebb246)">Diff</a>

Fix editorial issues in The Role of Human-Friendly Identifiers section.

---

index.html

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/742.html" title="Last updated on May 29, 2021, 7:33 PM UTC (365e0b3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/742/ab18a18...365e0b3.html" title="Last updated on May 29, 2021, 7:33 PM UTC (365e0b3)">Diff</a>

Update Verification Method Revocation section.

---

index.html

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/743.html" title="Last updated on May 19, 2021, 12:43 AM UTC (ac95c53)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/743/ab18a18...ac95c53.html" title="Last updated on May 19, 2021, 12:43 AM UTC (ac95c53)">Diff</a>

Fix editorial issues with DID Recovery section.

---

index.html

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/752.html" title="Last updated on May 24, 2021, 1:14 AM UTC (a0eb6ba)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/752/435a304...a0eb6ba.html" title="Last updated on May 24, 2021, 1:14 AM UTC (a0eb6ba)">Diff</a>

Fix editorial issues with Level of Assurance section.

---

index.html

Removes the "at risk" notes.
Tests for two implementations are now in the DID test suite:
- did:ion - https://github.com/w3c/did-test-suite/blob/cff8582/packages/did-core-test-server/suites/implementations/did-ion.json#L65-L68
- did:orb - https://github.com/w3c/did-test-suite/blob/cff8582/packages/did-core-test-server/suites/implementations/did-orb.json#L501-L505
***
<a href="https://pr-preview.s3.amazonaws.com/troyronda/did-core/pull/756.html" title="Last updated on May 27, 2021, 1:18 PM UTC (91702ba)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/756/435a304...troyronda:91702ba.html" title="Last updated on May 27, 2021, 1:18 PM UTC (91702ba)">Diff</a>

Remove at risk note for equivalentId and canonicalId

---

index.html

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/761.html" title="Last updated on May 30, 2021, 8:00 PM UTC (183e719)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/761/93b0b06...183e719.html" title="Last updated on May 30, 2021, 8:00 PM UTC (183e719)">Diff</a>

Editorial fixes to DID Document Correlation Risks section.

---

index.html

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/741.html" title="Last updated on May 29, 2021, 7:17 PM UTC (7bce470)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/741/ab18a18...7bce470.html" title="Last updated on May 29, 2021, 7:17 PM UTC (7bce470)">Diff</a>

Update Verification Method Rotation section.

---

index.html

This is an initial set of text proposal to address issue #708
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/764.html" title="Last updated on Jun 27, 2021, 11:09 PM UTC (245e020)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/764/5ffbdd1...245e020.html" title="Last updated on Jun 27, 2021, 11:09 PM UTC (245e020)">Diff</a>

docs: add notes to nudge implementors towards common DID URL patterns

---

index.html

For #625
This adds descriptions for the five diagrams in Section C:
figure id|image
-|-
[`did-and-did-document-graph`](https://www.w3.org/TR/did-core/#did-and-did-document-graph) | [`figure-a.1-did-and-did-document-graph.png`](https://github.com/w3c/did-core/blob/cd6ee4836e8cede5a475c341b840b3f11d2a3200/diagrams/figure-a.1-did-and-did-document-graph.png)
[`alsoKnownAs-graph`](https://www.w3.org/TR/did-core/#alsoKnownAs-graph) | [`figure-a.2-also-known-as-graph.png`](https://github.com/w3c/did-core/blob/cd6ee4836e8cede5a475c341b840b3f11d2a3200/diagrams/figure-a.2-also-known-as-graph.png)
[`controller-subject-equivalence`](https://www.w3.org/TR/did-core/#controller-subject-equivalence) | [`figure-b.1-controller-and-subject-equivalence.png`](https://github.com/w3c/did-core/blob/cd6ee4836e8ced …

Add detailed description for figures in Section C (Architectural Considerations)

---

index.html

This PR:
1. changes the order of verification material so that the "non-normative" feature is defined after the normative one.
2. adds a warning about `privateKeyMultibase` representations potentially not existing.
https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/772.html#dfn-publickeymultibase
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/772.html" title="Last updated on Jul 14, 2021, 9:49 PM UTC (6c4fbfc)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/772/cd6ee48...6c4fbfc.html" title="Last updated on Jul 14, 2021, 9:49 PM UTC (6c4fbfc)">Diff</a>

Add warning about publicKeyMultibase

---

common.js
index.html

I did it guys! 
I'm not completely inept. :P 
...after 5 long years, the DID specification finally links to its use cases document.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/774.html" title="Last updated on Jul 12, 2021, 1:59 PM UTC (b6e0136)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/774/b57167a...b6e0136.html" title="Last updated on Jul 12, 2021, 1:59 PM UTC (b6e0136)">Diff</a>

Add links to use cases document. Consolidate other useful links.

---

index.html

This PR just rearranges the order of the appendices to make the specification easier to read. Examples are put at the head of the appendix, IANA considerations at the very end, etc. This is purely editorial, no changes were made to the appendices other than changing the order in which they appear in the specification.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/777.html" title="Last updated on Jul 11, 2021, 7:11 PM UTC (716802e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/777/b57167a...716802e.html" title="Last updated on Jul 11, 2021, 7:11 PM UTC (716802e)">Diff</a>

Rearrange the order of the appendices.

---

index.html

This PR creates a new "Revision History" section and adds updates made during the second Candidate Recommendation phase.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/779.html" title="Last updated on Jul 17, 2021, 5:55 PM UTC (490815d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/779/b57167a...490815d.html" title="Last updated on Jul 17, 2021, 5:55 PM UTC (490815d)">Diff</a>

Move revision history to appendix and add new items based on 2nd CR.

---

index.html

This adds descriptions for the following three diagrams, for #625, in the style of #771 as modified by 6ada0def45b0df7cb52c3587d5fce5ce6a32dfc5 and b57167a705549a7587d2617391f66257ea3f16f7.
section|figure id|image
-|-|-
1.3 | [`brief-architecture-overview`](https://www.w3.org/TR/did-core/#brief-architecture-overview) | [`diagrams/did_brief_architecture_overview.svg`](https://github.com/w3c/did-core/blob/b57167a705549a7587d2617391f66257ea3f16f7/diagrams/did_brief_architecture_overview.svg)
4   | [`did-document-entries`](https://www.w3.org/TR/did-core/#did-document-entries) | [`diagrams/diagram-did-document-entries.svg`](https://github.com/w3c/did-core/blob/b57167a705549a7587d2617391f66257ea3f16f7/diagrams/diagram-did-document-entries.svg)
6.1 | …

Add detailed description for three diagrams

---

index.html

Use common doc style of a single space after periods.
***
<a href="https://pr-preview.s3.amazonaws.com/davidlehn/did-core/pull/782.html" title="Last updated on Jul 13, 2021, 4:48 PM UTC (1a79fc8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/782/b57167a...davidlehn:1a79fc8.html" title="Last updated on Jul 13, 2021, 4:48 PM UTC (1a79fc8)">Diff</a>

Normalize period spacing.

---

index.html

Removes at-risk marker for `alsoKnownAs`.
Raised as an alternative to #776 and as an addition to #775, in an attempt to make @msporny life a tad easier should implementers meet the deadline set in the DID WG meeting 7/13/21.
Should only be merged if that deadline is met.
(Can also be closed without prejudice if Manu's life is easier without it)
Signed-off-by: Brent Zundel <brent.zundel@gmail.com>
***
<a href="https://pr-preview.s3.amazonaws.com/brentzundel/did-spec/pull/783.html" title="Last updated on Jul 13, 2021, 5:00 PM UTC (789dc36)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/783/b57167a...brentzundel:789dc36.html" title="Last updated on Jul 13, 2021, 5:00 PM UTC (789dc36)">Diff</a>

remove at-risk marker for alsoKnownAs

---

index.html

This adds long descriptions for additional two diagrams:
- https://www.w3.org/TR/did-core/#resolve-resolverepresentation
- https://www.w3.org/TR/did-core/#did-url-dereference-overview
This uses the same approach as in https://github.com/w3c/did-core/pull/781, and partially re-uses @clehner 's content from that PR for a similar diagram here.
Partially addresses https://github.com/w3c/did-core/issues/625.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/785.html" title="Last updated on Jul 14, 2021, 4:01 PM UTC (8c3b32f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/785/b57167a...8c3b32f.html" title="Last updated on Jul 14, 2021, 4:01 PM UTC (8c3b32f)">Diff</a>

 Add detailed description for two diagrams

---

index.html

This PR updates the IANA guidance for `application/did+ld+json` to make it clear that the media type is safe to use (based on implementation experience), provides the current state of affairs with the IETF mediaman WG, and an expected outcome and registration expectation.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/778.html" title="Last updated on Jul 17, 2021, 6:20 PM UTC (5d87659)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/778/0319f89...5d87659.html" title="Last updated on Jul 17, 2021, 6:20 PM UTC (5d87659)">Diff</a>

Update the IANA guidance due to IETF mediaman WG.

---

index.html

This is the final **PROPOSED** list of Editors, Authors, and Acknowledgements. It was generated by pulling data from a variety of places (trying to be as data driven as possible). 
The Acknowledgements include every individual, in alphabetical order, that ever made a comment on an issue or PR over the years in Github.
The Editors are pulled directly from the contributor graph. The people in the top contributors by commits and lines changed are the Editors. There is a significant drop off in contribution after the 3rd person in the list for the DID Core specification.
https://github.com/w3c/did-core/graphs/contributors
The Authors list is a little more squishy. It's an amalgamation of contributions over the years that provided multiple significant architectural foundations as well as more …

Update Editors, Authors, and Acknowledgements.

---

index.html

The chairs have decided the ordering of the author's list should be: Manu Sporny, Dave Longley, Markus Sabadello, Drummond Reed, Orie Steele, Christopher Allen. This PR makes that change.
Signed-off-by: Brent Zundel <brent.zundel@gmail.com>
***
<a href="https://pr-preview.s3.amazonaws.com/brentzundel/did-spec/pull/788.html" title="Last updated on Jul 19, 2021, 11:12 PM UTC (073bc53)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/788/69677ff...brentzundel:073bc53.html" title="Last updated on Jul 19, 2021, 11:12 PM UTC (073bc53)">Diff</a>

Chair's decision for ordering author's list

---

index.html

This adds a brief historical perspective on the specification before it entered the DID WG and acknowledges/appreciates the individuals that worked on the proto-documents that led to the DID Specification.
See the new text here: https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/790.html#acknowledgements
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/790.html" title="Last updated on Sep 11, 2021, 10:21 PM UTC (77dab87)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/790/c672e55...77dab87.html" title="Last updated on Sep 11, 2021, 10:21 PM UTC (77dab87)">Diff</a>

Add brief historical perspective in acknowledgements.

---

index.html
terms.html

This is intended as an editorial change to enable the term to be more easily referenced from other documents.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/792.html" title="Last updated on Aug 23, 2021, 4:16 PM UTC (6898a21)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/792/c672e55...6898a21.html" title="Last updated on Aug 23, 2021, 4:16 PM UTC (6898a21)">Diff</a>

Add definition for representation-specific entries

---

errata.html
index.html

The labels `PossibleErratum` and `Errata` have been added to the repo and the `editorial` has been changed to `Editorial` to avoid possible problems with the underlying scripts.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/793.html" title="Last updated on Sep 11, 2021, 10:27 PM UTC (07e7df7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/793/c672e55...07e7df7.html" title="Last updated on Sep 11, 2021, 10:27 PM UTC (07e7df7)">Diff</a>

Added the errata management

---

REC/2022-07-19/index.html

@msporny I also took the liberty of applying this change directly
on the version hosted on w3.org/TR ,
as I notived this paragraph was not on the REC dated 2022-06-30.
I don't know why/how it popped back...

remove PR-related paragraph from REC

---

index.html

This PR fixes issue #791 by explicitly marking all appendices are non-normative.
I will merge this PR as soon as I have confirmation from the Chairs and Staff since this is a purely editorial change with no additions nor changes to existing specification text.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/796.html" title="Last updated on Sep 13, 2021, 1:54 AM UTC (a9349a7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/796/d20b7c7...a9349a7.html" title="Last updated on Sep 13, 2021, 1:54 AM UTC (a9349a7)">Diff</a>
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/796.html" title="Last updated on Jul 7, 2024, 6:54 PM UTC (a9349a7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/796/d20b7c7...a9349a7.htm …

Clarify that appendices are non-normative.

---

index.html

This PR adds a non-normative appendix section on resource usage trade-offs and points readers to the DID Rubric for further evaluation criteria.
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Oct 6, 2021, 12:46 AM UTC)_.
<details>
:rotating_light: [Spec Generator](https://www.w3.org/2015/labs/) - Spec Generator is the web service used to build specs that rely on ReSpec.
:link: [Related URL](https://labs.w3.org/spec-generator/?type=respec&url=https%3A%2F%2Frawcdn.githack.com%2Fw3c%2Fdid-core%2Fe95f2b33d16606bb6a4ea211082f4b9e8e68f235%2Findex.html%3FisPreview%3Dtrue)
_If you don't have enough information above to …

Add section on Evaluating Competing Considerations.

---

index.html

This PR fixes the `publicKeyMultibase` values in the specification to ensure that they're correctly encoded.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/807.html" title="Last updated on Dec 8, 2021, 8:51 PM UTC (685b441)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/807/d20b7c7...685b441.html" title="Last updated on Dec 8, 2021, 8:51 PM UTC (685b441)">Diff</a>

Ensure publicKeyMultibase values are valid.

---

index.html

The INFRA citations for maps in `serviceEndpoint` were for string instead of map. This PR updates the citations to correspond with the text.
***
<a href="https://pr-preview.s3.amazonaws.com/clehner/did-core/pull/815.html" title="Last updated on Jan 26, 2022, 7:20 PM UTC (16b7c8f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/815/d20b7c7...clehner:16b7c8f.html" title="Last updated on Jan 26, 2022, 7:20 PM UTC (16b7c8f)">Diff</a>

Fix reference to maps

---

index.html

Fixes https://github.com/w3c/did-core/issues/816.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/817.html" title="Last updated on Feb 3, 2022, 3:46 PM UTC (e2fba44)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/817/d20b7c7...e2fba44.html" title="Last updated on Feb 3, 2022, 3:46 PM UTC (e2fba44)">Diff</a>

Add missing "of" word

---

index.html

addresses issue #819 by removing the wrong link from `VerificationMethod::controller` to the definition of `DIDDocument::controller`.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/820.html" title="Last updated on Mar 2, 2022, 11:57 AM UTC (decb9e8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/820/d20b7c7...decb9e8.html" title="Last updated on Mar 2, 2022, 11:57 AM UTC (decb9e8)">Diff</a>

remove link to wrong controller definition

---

index.html

I found a small syntax error in the first JSON example. Here is the fix.
***
<a href="https://pr-preview.s3.amazonaws.com/wagner-daniel/did-core/pull/824.html" title="Last updated on Jun 16, 2022, 5:23 PM UTC (6d1ddd4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/824/d20b7c7...wagner-daniel:6d1ddd4.html" title="Last updated on Jun 16, 2022, 5:23 PM UTC (6d1ddd4)">Diff</a>

Fix JSON syntax in simple DID document

---

index.html

Just fixing some links
***
<a href="https://pr-preview.s3.amazonaws.com/FabioPinheiro/did-core/pull/840.html" title="Last updated on Apr 5, 2023, 12:32 AM UTC (2c7886b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/840/e9959f9...FabioPinheiro:2c7886b.html" title="Last updated on Apr 5, 2023, 12:32 AM UTC (2c7886b)">Diff</a>

Fix link to INFRA#maps in index.html

---

index.html

***
<a href="https://pr-preview.s3.amazonaws.com/gobengo/did-core/pull/848.html" title="Last updated on Dec 11, 2023, 12:53 AM UTC (548c7ac)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/848/a8ddc80...gobengo:548c7ac.html" title="Last updated on Dec 11, 2023, 12:53 AM UTC (548c7ac)">Diff</a>

add a missing comma in example 1 json

---

index.html

A comprehensive update of https://github.com/w3c/did-core/pull/824 by fixing all relevant examples.
***
<a href="https://pr-preview.s3.amazonaws.com/denkeni/did-core/pull/856.html" title="Last updated on Jul 18, 2024, 5:37 PM UTC (ae7c621)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/856/c620ce9...denkeni:ae7c621.html" title="Last updated on Jul 18, 2024, 5:37 PM UTC (ae7c621)">Diff</a>

Fix JSON formatting for DID document

---

index.html

The DID parameter values that we had in the specification were never properly URI Encoded per the rules for query parameters in RFC3986 (which is what we normatively reference). This PR fixes that, and is an editorial change (because it only updates examples). We got the normative reference right, but flubbed on the DID parameter examples.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/813.html" title="Last updated on Aug 15, 2024, 6:45 PM UTC (aa14fcd)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/813/d20b7c7...aa14fcd.html" title="Last updated on Aug 15, 2024, 6:45 PM UTC (aa14fcd)">Diff</a>

Fix improperly URI Encoded values in DID parameters.

---

index.html

See https://github.com/w3c/did-core/pull/868/files#r1844058199
The reference wasn't removed by that PR, and it remained in [main](https://github.com/w3c/did-core/blob/308b4c1b349060e5304f818ab47a8d16d480a817/index.html#L5566-L5567) at the time I created this PR to remove it.
***
<a href="https://pr-preview.s3.amazonaws.com/TallTed/did-core/pull/871.html" title="Last updated on Nov 15, 2024, 3:51 PM UTC (1521ab7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/871/308b4c1...TallTed:1521ab7.html" title="Last updated on Nov 15, 2024, 3:51 PM UTC (1521ab7)">Diff</a>

removes normative reference discussed in #868

---

index.html
terms.html

This removes the "DID Parameters" section from did-core. Also see the "matching" PR in did-resolution: https://github.com/w3c/did-resolution/pull/106
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/872.html" title="Last updated on Dec 19, 2024, 6:29 PM UTC (831b95f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/872/1737b58...831b95f.html" title="Last updated on Dec 19, 2024, 6:29 PM UTC (831b95f)">Diff</a>

Move DID Parameters section from did-core to did-resolution.

---

index.html

Addresses #860
Let me know if the comments I added to the example are overkill. Happy to remove.
I also note that [example 9](https://www.w3.org/TR/did-core/#example-an-example-of-a-relative-did-url) does capture some of this. I wanted to add an example that shows a relative DID URL being used as a verificationMethod ID.
***
<a href="https://pr-preview.s3.amazonaws.com/wip-abramson/did-core/pull/874.html" title="Last updated on Jan 3, 2025, 10:20 AM UTC (5c2d5de)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/874/3fa1d8d...wip-abramson:5c2d5de.html" title="Last updated on Jan 3, 2025, 10:20 AM UTC (5c2d5de)">Diff</a>

Add relative DID URL DID Document example

---

index.html

Hopefully this clarifies the confusion raised in #812
***
<a href="https://pr-preview.s3.amazonaws.com/wip-abramson/did-core/pull/875.html" title="Last updated on Jan 8, 2025, 2:43 PM UTC (c55f6cc)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/875/3fa1d8d...wip-abramson:c55f6cc.html" title="Last updated on Jan 8, 2025, 2:43 PM UTC (c55f6cc)">Diff</a>

Improve capability delegation example and explanation

---

index.html

This PR is an attempt to address issue #873 by linking to the fragment resolution algorithm in the CID specification..
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did/pull/882.html" title="Last updated on Mar 3, 2025, 5:08 PM UTC (078227d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did/882/6939993...078227d.html" title="Last updated on Mar 3, 2025, 5:08 PM UTC (078227d)">Diff</a>

Add link to fragment resolution algorithm.

---

index.html

This PR is an attempt to address issue #839 by adding text clarifying where group controllers might be listed.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did/pull/883.html" title="Last updated on Mar 26, 2025, 3:44 PM UTC (5caf733)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did/883/6939993...5caf733.html" title="Last updated on Mar 26, 2025, 3:44 PM UTC (5caf733)">Diff</a>

Add text clarifying where group controllers might be listed.

---

index.html

This PR is an attempt to address issue #337 by clarifying specific existing (and presumed) restrictions on DID Document identifiers (such as parameters and fragment identifiers).
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did/pull/886.html" title="Last updated on Apr 3, 2025, 11:56 PM UTC (cc33250)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did/886/ffc61ef...cc33250.html" title="Last updated on Apr 3, 2025, 11:56 PM UTC (cc33250)">Diff</a>

Clarify restrictions on identifiers used in DID documents.

---

.github/workflows/auto-publish.yml

I realize that Echidna was never re-enabled since we published our FPWD. This should no the trick.

re-enable Echidna

---

index.html

This PR is an attempt to address issue #855 by simplifying the abstract data model down to INFRA and specifying a single concrete JSON representation. 
Note: We are currently in maintenance mode, which means that we cannot make any class 4 changes (change normative statements in ways that are not backwards compatible). That has hampered a more straightforward PR and required some normative acrobatics given that I couldn't remove previous normative statements. Please keep this in mind as you review as some wording is painfully contrived due to our maintenance mode status with this specification.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did/pull/887.html" title="Last updated on Apr 24, 2025, 1:47 PM UTC (42d0bd1)">Preview</a> | <a …

Simplify abstract data model and specify one concrete representation

---

.github/workflows/vocabulary.yml
vocab/v11/template.html
vocab/v11/vocabulary.yml

This is the PR on issue #884. It includes the vocabulary description file in YAML, the HTML template file, and also includes a GitHub action to generate the HTML, Turtle, and JSON-LD files, as well as the `@context` file.
The generated files can be preview-d at https://w3c.github.io/yml2vocab/previews/did/.
More information on the underlying tool can be found at https://github.com/w3c/yml2vocab, with the corresponding package being available on [npm](https://www.npmjs.com/package/yml2vocab) and on [jsr](https://jsr.io/@iherman/yml2vocab).

Added the necessary files for vocabulary deployment

---

index.html

This PR is an attempt to address issue #866 by clarifying that temporary `id` values might exist during certain DID operations.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did/pull/894.html" title="Last updated on Jul 10, 2025, 1:39 PM UTC (36d837b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did/894/d0be1f3...36d837b.html" title="Last updated on Jul 10, 2025, 1:39 PM UTC (36d837b)">Diff</a>

Clarify that temporary `id` values might be used during operations.

---

index.html

This PR is an attempt to address issue #865 by adding a warning about comparing DID URLs that contain more than a single query parameter.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did/pull/895.html" title="Last updated on Jul 10, 2025, 1:42 PM UTC (c3a8092)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did/895/d0be1f3...c3a8092.html" title="Last updated on Jul 10, 2025, 1:42 PM UTC (c3a8092)">Diff</a>

Add warning about comparing DID URLs containing query parameters.

---

index.html

This PR is an attempt to address issue #898 by removing a confusing fragment example from the spec and fixing some of the fragment naming to make it easier to understand what the fragment is pointing to.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did/pull/904.html" title="Last updated on Aug 28, 2025, 10:18 PM UTC (4b92154)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did/904/3ab8b19...4b92154.html" title="Last updated on Aug 28, 2025, 10:18 PM UTC (4b92154)">Diff</a>

Fix DID fragment examples.
